var nepalJson = {
  "province": [
    {"id": 1, "text": "Province No.1", "textNP": "प्रदेश नंबर १"},
    {"id": 2, "text": "Madhesh Province", "textNP": "मधेश प्रदेश"},
    {"id": 3, "text": "Bagmati Province", "textNP": "बाग्मती प्रदेश"},
    {"id": 4, "text": "Gandaki Province", "textNP": "गण्डकी प्रदेश"},
    {"id": 5, "text": "Lumbini Provience", "textNP": "लुम्बिनी प्रदेश"},
    {"id": 6, "text": "Karnali Province", "textNP": "कर्णाली प्रदेश"},
    {"id": 7, "text": "Sudur Paschim Province", "textNP": "सुदूर पश्चिम प्रदेश"}
  ],
  "zone": [
    {"id": 1, "text": "Mechi", "textNP": "मेची"},
    {"id": 2, "text": "Koshi", "textNP": "कोशी"},
    {"id": 3, "text": "Sagarmatha", "textNP": "सगरमाथा"},
    {"id": 4, "text": "Janakpur", "textNP": "जनकपुर"},
    {"id": 5, "text": "Bagmati", "textNP": "बागमति"},
    {"id": 6, "text": "Narayani", "textNP": "नारायणी"},
    {"id": 7, "text": "Gandaki", "textNP": "गण्डकी"},
    {"id": 8, "text": "Dhawalagiri", "textNP": "धवलागिरी"},
    {"id": 9, "text": "Lumbini", "textNP": "लुम्विनी"},
    {"id": 10, "text": "Rapti", "textNP": "राप्ती"},
    {"id": 11, "text": "Bheri", "textNP": "भेरी"},
    {"id": 12, "text": "Karnali", "textNP": "कर्णाली"},
    {"id": 13, "text": "Seti", "textNP": "सेती"},
    {"id": 14, "text": "Mahakali", "textNP": "महाकाली"}
  ],
  "district": [
    {
      "id": 1,
      "zoneid": 1,
      "stateid": 1,
      "text": "Taplejung",
      "textNP": "ताप्लेजुंग "
    },
    {
      "id": 2,
      "zoneid": 1,
      "stateid": 1,
      "text": "Panchthar",
      "textNP": "पांचथर "
    },
    {"id": 3, "zoneid": 1, "stateid": 1, "text": "Ilam", "textNP": "इलाम "},
    {"id": 4, "zoneid": 1, "stateid": 1, "text": "Jhapa", "textNP": "झापा "},
    {"id": 5, "zoneid": 2, "stateid": 1, "text": "Morang", "textNP": "मोरंग "},
    {"id": 6, "zoneid": 2, "stateid": 1, "text": "Sunsari", "textNP": "सुनसरी"},
    {
      "id": 7,
      "zoneid": 2,
      "stateid": 1,
      "text": "Dhankutta",
      "textNP": "धनकुटा "
    },
    {
      "id": 8,
      "zoneid": 2,
      "stateid": 1,
      "text": "Sankhuwasabha",
      "textNP": "संखुवासभा "
    },
    {
      "id": 9,
      "zoneid": 2,
      "stateid": 1,
      "text": "Bhojpur",
      "textNP": "भोजपुर "
    },
    {
      "id": 10,
      "zoneid": 2,
      "stateid": 1,
      "text": "Terhathum",
      "textNP": "तेह्रथुम "
    },
    {
      "id": 11,
      "zoneid": 3,
      "stateid": 1,
      "text": "Okhaldunga",
      "textNP": "ओखलढुंगा "
    },
    {
      "id": 12,
      "zoneid": 3,
      "stateid": 1,
      "text": "Khotang",
      "textNP": "खोटाँग "
    },
    {
      "id": 13,
      "zoneid": 3,
      "stateid": 1,
      "text": "Solukhumbu",
      "textNP": "सोलुखुम्बू "
    },
    {
      "id": 14,
      "zoneid": 3,
      "stateid": 1,
      "text": "Udaypur",
      "textNP": "उदयपुर "
    },
    {
      "id": 15,
      "zoneid": 3,
      "stateid": 2,
      "text": "Saptari",
      "textNP": "सप्तरी "
    },
    {
      "id": 16,
      "zoneid": 3,
      "stateid": 2,
      "text": "Siraha",
      "textNP": "सिराहा "
    },
    {
      "id": 17,
      "zoneid": 4,
      "stateid": 2,
      "text": "Dhanusa",
      "textNP": "धनुषा "
    },
    {
      "id": 18,
      "zoneid": 4,
      "stateid": 2,
      "text": "Mahottari",
      "textNP": "महोत्तरी "
    },
    {
      "id": 19,
      "zoneid": 4,
      "stateid": 2,
      "text": "Sarlahi",
      "textNP": "सर्लाही "
    },
    {
      "id": 20,
      "zoneid": 4,
      "stateid": 3,
      "text": "Sindhuli",
      "textNP": "सिन्धुली "
    },
    {
      "id": 21,
      "zoneid": 4,
      "stateid": 3,
      "text": "Ramechhap",
      "textNP": "रामेछाप "
    },
    {"id": 22, "zoneid": 4, "stateid": 3, "text": "Dolkha", "textNP": "दोलखा"},
    {
      "id": 23,
      "zoneid": 5,
      "stateid": 3,
      "text": "Sindhupalchauk",
      "textNP": "सिन्धुपाल्चोक "
    },
    {
      "id": 24,
      "zoneid": 5,
      "stateid": 3,
      "text": "Kavreplanchauk",
      "textNP": "काभ्रेपलान्चोक "
    },
    {
      "id": 25,
      "zoneid": 5,
      "stateid": 3,
      "text": "Lalitpur",
      "textNP": "ललितपुर "
    },
    {
      "id": 26,
      "zoneid": 5,
      "stateid": 3,
      "text": "Bhaktapur",
      "textNP": "भक्तपुर "
    },
    {
      "id": 27,
      "zoneid": 5,
      "stateid": 3,
      "text": "Kathmandu",
      "textNP": "काठमाडौँ "
    },
    {
      "id": 28,
      "zoneid": 5,
      "stateid": 3,
      "text": "Nuwakot",
      "textNP": "नुवाकोट "
    },
    {"id": 29, "zoneid": 5, "stateid": 3, "text": "Rasuwa", "textNP": "रसुवा "},
    {"id": 30, "zoneid": 5, "stateid": 3, "text": "Dhading", "textNP": "धादिङ"},
    {
      "id": 31,
      "zoneid": 6,
      "stateid": 3,
      "text": "Makwanpur",
      "textNP": "मकवानपुर "
    },
    {
      "id": 32,
      "zoneid": 6,
      "stateid": 2,
      "text": "Rauthat",
      "textNP": "रौतहट "
    },
    {"id": 33, "zoneid": 6, "stateid": 2, "text": "Bara", "textNP": "बारा "},
    {"id": 34, "zoneid": 6, "stateid": 2, "text": "Parsa", "textNP": "पर्सा "},
    {"id": 35, "zoneid": 6, "stateid": 3, "text": "Chitwan", "textNP": "चितवन"},
    {"id": 36, "zoneid": 7, "stateid": 4, "text": "Gorkha", "textNP": "गोरखा "},
    {
      "id": 37,
      "zoneid": 7,
      "stateid": 4,
      "text": "Lamjung",
      "textNP": "लमजुङ "
    },
    {
      "id": 38,
      "zoneid": 7,
      "stateid": 4,
      "text": "Tanahun",
      "textNP": "तनहुँ "
    },
    {
      "id": 39,
      "zoneid": 7,
      "stateid": 4,
      "text": "Syangja",
      "textNP": "स्याङग्जा"
    },
    {"id": 40, "zoneid": 7, "stateid": 4, "text": "Kaski", "textNP": "कास्की "},
    {"id": 41, "zoneid": 7, "stateid": 4, "text": "Manag", "textNP": "मनाङ "},
    {
      "id": 42,
      "zoneid": 8,
      "stateid": 4,
      "text": "Mustang",
      "textNP": "मुस्ताङ "
    },
    {"id": 43, "zoneid": 8, "stateid": 4, "text": "Parwat", "textNP": "पर्वत "},
    {
      "id": 44,
      "zoneid": 8,
      "stateid": 4,
      "text": "Myagdi",
      "textNP": "म्याग्दी "
    },
    {
      "id": 45,
      "zoneid": 8,
      "stateid": 4,
      "text": "Baglung",
      "textNP": "बागलुङ"
    },
    {"id": 46, "zoneid": 9, "stateid": 5, "text": "Gulmi", "textNP": "गुल्मी "},
    {"id": 47, "zoneid": 9, "stateid": 5, "text": "Palpa", "textNP": "पाल्पा "},
    {
      "id": 48,
      "zoneid": 9,
      "stateid": 4,
      "text": "Nawalpur",
      "textNP": "नवलपुर "
    },
    {"id": 49, "zoneid": 9, "stateid": 5, "text": "Parasi", "textNP": "परासी "},
    {
      "id": 50,
      "zoneid": 9,
      "stateid": 5,
      "text": "Rupandehi",
      "textNP": "रुपन्देही "
    },
    {
      "id": 51,
      "zoneid": 9,
      "stateid": 5,
      "text": "Arghakhanchi",
      "textNP": "अर्घाखाँची "
    },
    {
      "id": 52,
      "zoneid": 9,
      "stateid": 5,
      "text": "Kapilvastu",
      "textNP": "कपिलवस्तु "
    },
    {
      "id": 53,
      "zoneid": 10,
      "stateid": 5,
      "text": "Pyuthan",
      "textNP": "प्युठान "
    },
    {
      "id": 54,
      "zoneid": 10,
      "stateid": 5,
      "text": "Rolpa",
      "textNP": "रोल्पा "
    },
    {
      "id": 55,
      "zoneid": 10,
      "stateid": 5,
      "text": "Rukum Purba",
      "textNP": "पूर्वी रूकुम "
    },
    {
      "id": 56,
      "zoneid": 10,
      "stateid": 6,
      "text": "Rukum Paschim",
      "textNP": "पश्चिमी रूकुम "
    },
    {
      "id": 57,
      "zoneid": 10,
      "stateid": 6,
      "text": "Salyan",
      "textNP": "सल्यान "
    },
    {"id": 58, "zoneid": 10, "stateid": 5, "text": "Dang", "textNP": "दाङ "},
    {
      "id": 59,
      "zoneid": 11,
      "stateid": 5,
      "text": "Bardiya",
      "textNP": "बर्दिया "
    },
    {
      "id": 60,
      "zoneid": 11,
      "stateid": 6,
      "text": "Surkhet",
      "textNP": "सुर्खेत "
    },
    {
      "id": 61,
      "zoneid": 11,
      "stateid": 6,
      "text": "Dailekh",
      "textNP": "दैलेख "
    },
    {"id": 62, "zoneid": 11, "stateid": 5, "text": "Banke", "textNP": "बाँके "},
    {
      "id": 63,
      "zoneid": 11,
      "stateid": 6,
      "text": "Jajarkot",
      "textNP": "जाजरकोट "
    },
    {
      "id": 64,
      "zoneid": 12,
      "stateid": 6,
      "text": "Dolpa",
      "textNP": "डोल्पा "
    },
    {
      "id": 65,
      "zoneid": 12,
      "stateid": 6,
      "text": "Humla",
      "textNP": "हुम्ला "
    },
    {
      "id": 66,
      "zoneid": 12,
      "stateid": 6,
      "text": "Kalikot",
      "textNP": "कालिकोट "
    },
    {"id": 67, "zoneid": 12, "stateid": 6, "text": "Mugu", "textNP": "मुगु "},
    {"id": 68, "zoneid": 12, "stateid": 6, "text": "Jumla", "textNP": "जुम्ला"},
    {
      "id": 69,
      "zoneid": 13,
      "stateid": 7,
      "text": "Bajura",
      "textNP": "बाजुरा"
    },
    {
      "id": 70,
      "zoneid": 13,
      "stateid": 7,
      "text": "Bajhang",
      "textNP": "बझाङ "
    },
    {"id": 71, "zoneid": 13, "stateid": 7, "text": "Achham", "textNP": "अछाम "},
    {"id": 72, "zoneid": 13, "stateid": 7, "text": "Doti", "textNP": "डोटी "},
    {
      "id": 73,
      "zoneid": 1,
      "stateid": 7,
      "text": "Kailali",
      "textNP": "कैलाली "
    },
    {
      "id": 74,
      "zoneid": 14,
      "stateid": 7,
      "text": "Kanchanpur",
      "textNP": "कंचनपुर "
    },
    {
      "id": 75,
      "zoneid": 14,
      "stateid": 7,
      "text": "Dadeldhura",
      "textNP": "डडेलधुरा "
    },
    {
      "id": 76,
      "zoneid": 14,
      "stateid": 7,
      "text": "Baitadi",
      "textNP": "बैतडी "
    },
    {
      "id": 77,
      "zoneid": 14,
      "stateid": 7,
      "text": "Darchula",
      "textNP": "दार्चुला "
    }
  ],
  "vdc": [
    {"id": 1, "districtid": 1, "text": "Aathrai Tribeni Ga. Pa."},
    {"id": 2, "districtid": 1, "text": "Maiwakhola Ga. Pa."},
    {"id": 3, "districtid": 1, "text": "Meringden Ga. Pa."},
    {"id": 4, "districtid": 1, "text": "Mikwakhola Ga. Pa."},
    {"id": 5, "districtid": 1, "text": "Phaktanglung Ga. Pa."},
    {"id": 6, "districtid": 1, "text": "Phungling Na. Pa."},
    {"id": 7, "districtid": 1, "text": "Sidingba Ga. Pa."},
    {"id": 8, "districtid": 1, "text": "Sirijangha Ga. Pa."},
    {"id": 9, "districtid": 1, "text": "Pathibhara Yangwarak Ga. Pa."},
    {"id": 10, "districtid": 2, "text": "Falelung Ga. Pa."},
    {"id": 11, "districtid": 2, "text": "Falgunanda Ga. Pa."},
    {"id": 12, "districtid": 2, "text": "Hilihang Ga. Pa."},
    {"id": 13, "districtid": 2, "text": "Kummayak Ga. Pa."},
    {"id": 14, "districtid": 2, "text": "Miklajung Ga. Pa."},
    {"id": 15, "districtid": 2, "text": "Phidim Na. Pa."},
    {"id": 16, "districtid": 2, "text": "Tumbewa Ga. Pa."},
    {"id": 17, "districtid": 2, "text": "Yangwarak Ga. Pa."},
    {"id": 18, "districtid": 3, "text": "Chulachuli Ga. Pa."},
    {"id": 19, "districtid": 3, "text": "Deumai Na. Pa."},
    {"id": 20, "districtid": 3, "text": "Fakphokthum Ga. Pa."},
    {"id": 21, "districtid": 3, "text": "Illam Na. Pa."},
    {"id": 22, "districtid": 3, "text": "Mai Na. Pa."},
    {"id": 23, "districtid": 3, "text": "Maijogmai Ga. Pa."},
    {"id": 24, "districtid": 3, "text": "Mangsebung Ga. Pa."},
    {"id": 25, "districtid": 3, "text": "Rong Ga. Pa."},
    {"id": 26, "districtid": 3, "text": "Sandakpur Ga. Pa."},
    {"id": 27, "districtid": 3, "text": "Suryodaya Na. Pa."},
    {"id": 28, "districtid": 4, "text": "Arjundhara Na. Pa."},
    {"id": 29, "districtid": 4, "text": "Barhadashi Ga. Pa."},
    {"id": 30, "districtid": 4, "text": "Bhadrapur Na. Pa."},
    {"id": 31, "districtid": 4, "text": "Birtamod Na. Pa."},
    {"id": 32, "districtid": 4, "text": "Buddhashanti Ga. Pa."},
    {"id": 33, "districtid": 4, "text": "Damak Na. Pa."},
    {"id": 34, "districtid": 4, "text": "Gauradhaha Na. Pa."},
    {"id": 35, "districtid": 4, "text": "Gauriganj Ga. Pa."},
    {"id": 36, "districtid": 4, "text": "Haldibari Ga. Pa."},
    {"id": 37, "districtid": 4, "text": "Jhapa Ga. Pa."},
    {"id": 38, "districtid": 4, "text": "Kachankawal Ga. Pa."},
    {"id": 39, "districtid": 4, "text": "Kamal Ga. Pa."},
    {"id": 40, "districtid": 4, "text": "Kankai Na. Pa."},
    {"id": 41, "districtid": 4, "text": "Mechinagar Na. Pa."},
    {"id": 42, "districtid": 4, "text": "Shivasataxi Na. Pa."},
    {"id": 43, "districtid": 5, "text": "Belbari Na. Pa."},
    {"id": 44, "districtid": 5, "text": "Biratnagar Ma. Na. Pa."},
    {"id": 45, "districtid": 5, "text": "Budhiganga Ga. Pa."},
    {"id": 46, "districtid": 5, "text": "Dhanpalthan Ga. Pa."},
    {"id": 47, "districtid": 5, "text": "Gramthan Ga. Pa."},
    {"id": 48, "districtid": 5, "text": "Jahada Ga. Pa."},
    {"id": 49, "districtid": 5, "text": "Kanepokhari Ga. Pa."},
    {"id": 50, "districtid": 5, "text": "Katahari Ga. Pa."},
    {"id": 51, "districtid": 5, "text": "Kerabari Ga. Pa."},
    {"id": 52, "districtid": 5, "text": "Letang Na. Pa."},
    {"id": 53, "districtid": 5, "text": "Miklajung Ga. Pa."},
    {"id": 54, "districtid": 5, "text": "Patahrishanishchare Na. Pa."},
    {"id": 55, "districtid": 5, "text": "Rangeli Na. Pa."},
    {"id": 56, "districtid": 5, "text": "Ratuwamai Na. Pa."},
    {"id": 57, "districtid": 5, "text": "Sundarharaicha Na. Pa."},
    {"id": 58, "districtid": 5, "text": "Sunwarshi Na. Pa."},
    {"id": 59, "districtid": 5, "text": "Uralabari Na. Pa."},
    {"id": 60, "districtid": 6, "text": "Barah Na. Pa."},
    {"id": 61, "districtid": 6, "text": "Barju Ga. Pa."},
    {"id": 62, "districtid": 6, "text": "Bhokraha Narsingh Ga. Pa."},
    {"id": 63, "districtid": 6, "text": "Dewanganj Ga. Pa."},
    {"id": 64, "districtid": 6, "text": "Dharan Up. Ma. Na. Pa."},
    {"id": 65, "districtid": 6, "text": "Duhabi Na. Pa."},
    {"id": 66, "districtid": 6, "text": "Gadhi Ga. Pa."},
    {"id": 67, "districtid": 6, "text": "Harinagar Ga. Pa."},
    {"id": 68, "districtid": 6, "text": "Inaruwa Na. Pa."},
    {"id": 69, "districtid": 6, "text": "Itahari Up. Ma. Na. Pa."},
    {"id": 70, "districtid": 6, "text": "Koshi Ga. Pa."},
    {"id": 71, "districtid": 6, "text": "Ramdhuni Na. Pa."},
    {"id": 72, "districtid": 7, "text": "Chaubise Ga. Pa."},
    {"id": 73, "districtid": 7, "text": "Chhathar Jorpati Ga. Pa."},
    {"id": 74, "districtid": 7, "text": "Dhankuta Na. Pa."},
    {"id": 75, "districtid": 7, "text": "Shahidbhumi Ga. Pa."},
    {"id": 76, "districtid": 7, "text": "Sangurigadhi Ga. Pa."},
    {"id": 77, "districtid": 7, "text": "Mahalaxmi Na. Pa."},
    {"id": 78, "districtid": 7, "text": "Pakhribas Na. Pa."},
    {"id": 79, "districtid": 8, "text": "Bhotkhola Ga. Pa."},
    {"id": 80, "districtid": 8, "text": "Chainpur Na. Pa."},
    {"id": 81, "districtid": 8, "text": "Chichila Ga. Pa."},
    {"id": 82, "districtid": 8, "text": "Dharmadevi Na. Pa."},
    {"id": 83, "districtid": 8, "text": "Khandbari Na. Pa."},
    {"id": 84, "districtid": 8, "text": "Madi Na. Pa."},
    {"id": 85, "districtid": 8, "text": "Makalu Ga. Pa."},
    {"id": 86, "districtid": 8, "text": "Panchakhapan Na. Pa."},
    {"id": 87, "districtid": 8, "text": "Sabhapokhari Ga. Pa."},
    {"id": 88, "districtid": 8, "text": "Silichong Ga. Pa."},
    {"id": 89, "districtid": 9, "text": "Aamchowk Ga. Pa."},
    {"id": 90, "districtid": 9, "text": "Arun Ga. Pa."},
    {"id": 91, "districtid": 9, "text": "Bhojpur Na. Pa."},
    {"id": 92, "districtid": 9, "text": "Hatuwagadhi Ga. Pa."},
    {"id": 93, "districtid": 9, "text": "Pauwadungma Ga. Pa."},
    {"id": 94, "districtid": 9, "text": "Ramprasad Rai Ga. Pa."},
    {"id": 95, "districtid": 9, "text": "Salpasilichho Ga. Pa."},
    {"id": 96, "districtid": 9, "text": "Shadananda Na. Pa."},
    {"id": 97, "districtid": 9, "text": "Tyamkemaiyung Ga. Pa."},
    {"id": 98, "districtid": 10, "text": "Aathrai Ga. Pa."},
    {"id": 99, "districtid": 10, "text": "Chhathar Ga. Pa."},
    {"id": 100, "districtid": 10, "text": "Laligurans Na. Pa."},
    {"id": 101, "districtid": 10, "text": "Menchayam Ga. Pa."},
    {"id": 102, "districtid": 10, "text": "Myanglung Na. Pa."},
    {"id": 103, "districtid": 10, "text": "Phedap Ga. Pa."},
    {"id": 104, "districtid": 11, "text": "Champadevi Ga. Pa."},
    {"id": 105, "districtid": 11, "text": "Chisankhugadhi Ga. Pa."},
    {"id": 106, "districtid": 11, "text": "Khijidemba Ga. Pa."},
    {"id": 107, "districtid": 11, "text": "Likhu Ga. Pa."},
    {"id": 108, "districtid": 11, "text": "Manebhanjyang Ga. Pa."},
    {"id": 109, "districtid": 11, "text": "Molung Ga. Pa."},
    {"id": 110, "districtid": 11, "text": "Siddhicharan Na. Pa."},
    {"id": 111, "districtid": 11, "text": "Sunkoshi Ga. Pa."},
    {"id": 112, "districtid": 12, "text": "Ainselukhark Ga. Pa."},
    {"id": 113, "districtid": 12, "text": "Barahapokhari Ga. Pa."},
    {"id": 114, "districtid": 12, "text": "Diprung Ga. Pa."},
    {"id": 115, "districtid": 12, "text": "Halesi Tuwachung Na. Pa."},
    {"id": 116, "districtid": 12, "text": "Jantedhunga Ga. Pa."},
    {"id": 117, "districtid": 12, "text": "Kepilasagadhi Ga. Pa."},
    {"id": 118, "districtid": 12, "text": "Khotehang Ga. Pa."},
    {"id": 119, "districtid": 12, "text": "Rawa Besi Ga. Pa."},
    {"id": 120, "districtid": 12, "text": "Rupakot Majhuwagadhi Na. Pa."},
    {"id": 121, "districtid": 12, "text": "Sakela Ga. Pa."},
    {"id": 122, "districtid": 13, "text": "Thulung Dudhkoshi Ga. Pa."},
    {"id": 123, "districtid": 13, "text": "Dudhkoshi Ga. Pa."},
    {"id": 124, "districtid": 13, "text": "Khumbupasanglahmu Ga. Pa."},
    {"id": 125, "districtid": 13, "text": "Likhupike Ga. Pa."},
    {"id": 126, "districtid": 13, "text": "Mahakulung Ga. Pa."},
    {"id": 127, "districtid": 13, "text": "Nechasalyan Ga. Pa."},
    {"id": 128, "districtid": 13, "text": "Solududhakunda Na. Pa."},
    {"id": 129, "districtid": 13, "text": "Sotang Ga. Pa."},
    {"id": 130, "districtid": 14, "text": "Belaka Na. Pa."},
    {"id": 131, "districtid": 14, "text": "Chaudandigadhi Na. Pa."},
    {"id": 132, "districtid": 14, "text": "Katari Na. Pa."},
    {"id": 133, "districtid": 14, "text": "Rautamai Ga. Pa."},
    {"id": 134, "districtid": 14, "text": "Limchungbung Ga. Pa."},
    {"id": 135, "districtid": 14, "text": "Tapli Ga. Pa."},
    {"id": 136, "districtid": 14, "text": "Triyuga Na. Pa."},
    {"id": 137, "districtid": 14, "text": "Udayapurgadhi Ga. Pa."},
    {"id": 138, "districtid": 15, "text": "Agnisair Krishna Savaran Ga. Pa."},
    {"id": 139, "districtid": 15, "text": "Balan Bihul Ga. Pa."},
    {"id": 140, "districtid": 15, "text": "Belhi Chapena Ga. Pa."},
    {"id": 141, "districtid": 15, "text": "Bishnupur Ga. Pa."},
    {"id": 142, "districtid": 15, "text": "Bode Barsain Na. Pa."},
    {"id": 143, "districtid": 15, "text": "Chhinnamasta Ga. Pa."},
    {"id": 144, "districtid": 15, "text": "Dakneshwori Na. Pa."},
    {"id": 145, "districtid": 15, "text": "Hanumannagar Kankalini Na. Pa."},
    {"id": 146, "districtid": 15, "text": "Kanchanrup Na. Pa."},
    {"id": 147, "districtid": 15, "text": "Khadak Na. Pa."},
    {"id": 148, "districtid": 15, "text": "Mahadeva Ga. Pa."},
    {"id": 149, "districtid": 15, "text": "Rajbiraj Na. Pa."},
    {"id": 150, "districtid": 15, "text": "Rupani Ga. Pa."},
    {"id": 151, "districtid": 15, "text": "Saptakoshi Na. Pa."},
    {"id": 152, "districtid": 15, "text": "Shambhunath Na. Pa."},
    {"id": 153, "districtid": 15, "text": "Surunga Na. Pa."},
    {"id": 154, "districtid": 15, "text": "Tilathi Koiladi Ga. Pa."},
    {"id": 155, "districtid": 15, "text": "Tirahut Ga. Pa."},
    {"id": 156, "districtid": 16, "text": "Arnama Ga. Pa."},
    {"id": 157, "districtid": 16, "text": "Aurahi Ga. Pa."},
    {"id": 158, "districtid": 16, "text": "Bariyarpatti Ga. Pa."},
    {"id": 159, "districtid": 16, "text": "Bhagawanpur Ga. Pa."},
    {"id": 160, "districtid": 16, "text": "Bishnupur Ga. Pa."},
    {"id": 161, "districtid": 16, "text": "Dhangadhimai Na. Pa."},
    {"id": 162, "districtid": 16, "text": "Golbazar Na. Pa."},
    {"id": 163, "districtid": 16, "text": "Kalyanpur Na. Pa."},
    {"id": 164, "districtid": 16, "text": "Karjanha Na. Pa."},
    {"id": 165, "districtid": 16, "text": "Lahan Na. Pa."},
    {"id": 166, "districtid": 16, "text": "Laxmipur Patari Ga. Pa."},
    {"id": 167, "districtid": 16, "text": "Mirchaiya Na. Pa."},
    {"id": 168, "districtid": 16, "text": "Naraha Ga. Pa."},
    {"id": 169, "districtid": 16, "text": "Nawarajpur Ga. Pa."},
    {"id": 170, "districtid": 16, "text": "Sakhuwanankarkatti Ga. Pa."},
    {"id": 171, "districtid": 16, "text": "Siraha Na. Pa."},
    {"id": 172, "districtid": 16, "text": "Sukhipur Na. Pa."},
    {"id": 173, "districtid": 17, "text": "Aaurahi Ga. Pa."},
    {"id": 174, "districtid": 17, "text": "Bateshwor Ga. Pa."},
    {"id": 175, "districtid": 17, "text": "Bideha Na. Pa."},
    {"id": 176, "districtid": 17, "text": "Chhireshwornath Na. Pa."},
    {"id": 177, "districtid": 17, "text": "Dhanauji Ga. Pa."},
    {"id": 178, "districtid": 17, "text": "Dhanusadham Na. Pa."},
    {"id": 179, "districtid": 17, "text": "Ganeshman Charnath Na. Pa."},
    {"id": 180, "districtid": 17, "text": "Hansapur Na. Pa."},
    {"id": 181, "districtid": 17, "text": "Janaknandani Ga. Pa."},
    {"id": 182, "districtid": 17, "text": "Janakpur Up. Ma. Na. Pa."},
    {"id": 183, "districtid": 17, "text": "Kamala Na. Pa."},
    {"id": 184, "districtid": 17, "text": "Lakshminiya Ga. Pa."},
    {"id": 185, "districtid": 17, "text": "Mithila Na. Pa."},
    {"id": 186, "districtid": 17, "text": "Mithila Bihari Na. Pa."},
    {"id": 187, "districtid": 17, "text": "Mukhiyapatti Musarmiya Ga. Pa."},
    {"id": 188, "districtid": 17, "text": "Nagarain Na. Pa."},
    {"id": 189, "districtid": 17, "text": "Sabaila Na. Pa."},
    {"id": 190, "districtid": 17, "text": "Sahidnagar Na. Pa."},
    {"id": 191, "districtid": 18, "text": "Aurahi Na. Pa."},
    {"id": 192, "districtid": 18, "text": "Balwa Na. Pa."},
    {"id": 193, "districtid": 18, "text": "Bardibas Na. Pa."},
    {"id": 194, "districtid": 18, "text": "Bhangaha Na. Pa."},
    {"id": 195, "districtid": 18, "text": "Ekdanra Ga. Pa."},
    {"id": 196, "districtid": 18, "text": "Gaushala Na. Pa."},
    {"id": 197, "districtid": 18, "text": "Jaleswor Na. Pa."},
    {"id": 198, "districtid": 18, "text": "Loharpatti Na. Pa."},
    {"id": 199, "districtid": 18, "text": "Mahottari Ga. Pa."},
    {"id": 200, "districtid": 18, "text": "Manra Siswa Na. Pa."},
    {"id": 201, "districtid": 18, "text": "Matihani Na. Pa."},
    {"id": 202, "districtid": 18, "text": "Pipra Ga. Pa."},
    {"id": 203, "districtid": 18, "text": "Ramgopalpur Na. Pa."},
    {"id": 204, "districtid": 18, "text": "Samsi Ga. Pa."},
    {"id": 205, "districtid": 18, "text": "Sonama Ga. Pa."},
    {"id": 206, "districtid": 19, "text": "Bagmati Na. Pa."},
    {"id": 207, "districtid": 19, "text": "Balara Na. Pa."},
    {"id": 208, "districtid": 19, "text": "Barahathawa Na. Pa."},
    {"id": 209, "districtid": 19, "text": "Basbariya Ga. Pa."},
    {"id": 210, "districtid": 19, "text": "Bishnu Ga. Pa."},
    {"id": 211, "districtid": 19, "text": "Bramhapuri Ga. Pa."},
    {"id": 212, "districtid": 19, "text": "Chakraghatta Ga. Pa."},
    {"id": 213, "districtid": 19, "text": "Chandranagar Ga. Pa."},
    {"id": 214, "districtid": 19, "text": "Dhankaul Ga. Pa."},
    {"id": 215, "districtid": 19, "text": "Godaita Na. Pa."},
    {"id": 216, "districtid": 19, "text": "Haripur Na. Pa."},
    {"id": 217, "districtid": 19, "text": "Haripurwa Na. Pa."},
    {"id": 218, "districtid": 19, "text": "Hariwan Na. Pa."},
    {"id": 219, "districtid": 19, "text": "Ishworpur Na. Pa."},
    {"id": 220, "districtid": 19, "text": "Kabilasi Na. Pa."},
    {"id": 221, "districtid": 19, "text": "Kaudena Ga. Pa."},
    {"id": 222, "districtid": 19, "text": "Lalbandi Na. Pa."},
    {"id": 223, "districtid": 19, "text": "Malangawa Na. Pa."},
    {"id": 224, "districtid": 19, "text": "Parsa Ga. Pa."},
    {"id": 225, "districtid": 19, "text": "Ramnagar Ga. Pa."},
    {"id": 226, "districtid": 20, "text": "Dudhouli Na. Pa."},
    {"id": 227, "districtid": 20, "text": "Ghanglekh Ga. Pa."},
    {"id": 228, "districtid": 20, "text": "Golanjor Ga. Pa."},
    {"id": 229, "districtid": 20, "text": "Hariharpurgadhi Ga. Pa."},
    {"id": 230, "districtid": 20, "text": "Kamalamai Na. Pa."},
    {"id": 231, "districtid": 20, "text": "Marin Ga. Pa."},
    {"id": 232, "districtid": 20, "text": "Phikkal Ga. Pa."},
    {"id": 233, "districtid": 20, "text": "Sunkoshi Ga. Pa."},
    {"id": 234, "districtid": 20, "text": "Tinpatan Ga. Pa."},
    {"id": 235, "districtid": 21, "text": "Doramba Ga. Pa."},
    {"id": 236, "districtid": 21, "text": "Gokulganga Ga. Pa."},
    {"id": 237, "districtid": 21, "text": "Khadadevi Ga. Pa."},
    {"id": 238, "districtid": 21, "text": "Likhu Tamakoshi Ga. Pa."},
    {"id": 239, "districtid": 21, "text": "Manthali Na. Pa."},
    {"id": 240, "districtid": 21, "text": "Ramechhap Na. Pa."},
    {"id": 241, "districtid": 21, "text": "Sunapati Ga. Pa."},
    {"id": 242, "districtid": 21, "text": "Umakunda Ga. Pa."},
    {"id": 243, "districtid": 22, "text": "Baiteshwor Ga. Pa."},
    {"id": 244, "districtid": 22, "text": "Bhimeshwor Na. Pa."},
    {"id": 245, "districtid": 22, "text": "Bigu Ga. Pa."},
    {"id": 246, "districtid": 22, "text": "Gaurishankar Ga. Pa."},
    {"id": 247, "districtid": 22, "text": "Jiri Na. Pa."},
    {"id": 248, "districtid": 22, "text": "Kalinchok Ga. Pa."},
    {"id": 249, "districtid": 22, "text": "Melung Ga. Pa."},
    {"id": 250, "districtid": 22, "text": "Sailung Ga. Pa."},
    {"id": 251, "districtid": 22, "text": "Tamakoshi Ga. Pa."},
    {"id": 252, "districtid": 23, "text": "Balefi Ga. Pa."},
    {"id": 253, "districtid": 23, "text": "Barhabise Na. Pa."},
    {"id": 254, "districtid": 23, "text": "Bhotekoshi Ga. Pa."},
    {"id": 255, "districtid": 23, "text": "Chautara SangachokGadhi Na. Pa."},
    {"id": 256, "districtid": 23, "text": "Helambu Ga. Pa."},
    {"id": 257, "districtid": 23, "text": "Indrawati Ga. Pa."},
    {"id": 258, "districtid": 23, "text": "Jugal Ga. Pa."},
    {"id": 259, "districtid": 23, "text": "Lisangkhu Pakhar Ga. Pa."},
    {"id": 260, "districtid": 23, "text": "Melamchi Na. Pa."},
    {"id": 261, "districtid": 23, "text": "Panchpokhari Thangpal Ga. Pa."},
    {"id": 262, "districtid": 23, "text": "Sunkoshi Ga. Pa."},
    {"id": 263, "districtid": 23, "text": "Tripurasundari Ga. Pa."},
    {"id": 264, "districtid": 24, "text": "Banepa Na. Pa."},
    {"id": 265, "districtid": 24, "text": "Bethanchowk Ga. Pa."},
    {"id": 266, "districtid": 24, "text": "Bhumlu Ga. Pa."},
    {"id": 267, "districtid": 24, "text": "Chaurideurali Ga. Pa."},
    {"id": 268, "districtid": 24, "text": "Dhulikhel Na. Pa."},
    {"id": 269, "districtid": 24, "text": "Khanikhola Ga. Pa."},
    {"id": 270, "districtid": 24, "text": "Mahabharat Ga. Pa."},
    {"id": 271, "districtid": 24, "text": "Mandandeupur Na. Pa."},
    {"id": 272, "districtid": 24, "text": "Namobuddha Na. Pa."},
    {"id": 273, "districtid": 24, "text": "Panauti Na. Pa."},
    {"id": 274, "districtid": 24, "text": "Panchkhal Na. Pa."},
    {"id": 275, "districtid": 24, "text": "Roshi Ga. Pa."},
    {"id": 276, "districtid": 24, "text": "Temal Ga. Pa."},
    {"id": 277, "districtid": 25, "text": "Bagmati Ga. Pa."},
    {"id": 278, "districtid": 25, "text": "Godawari Na. Pa."},
    {"id": 279, "districtid": 25, "text": "Konjyosom Ga. Pa."},
    {"id": 280, "districtid": 25, "text": "Lalitpur Ma. Na. Pa."},
    {"id": 281, "districtid": 25, "text": "Mahalaxmi Na. Pa."},
    {"id": 282, "districtid": 25, "text": "Mahankal Ga. Pa."},
    {"id": 283, "districtid": 26, "text": "Bhaktapur Na. Pa."},
    {"id": 284, "districtid": 26, "text": "Changunarayan Na. Pa."},
    {"id": 285, "districtid": 26, "text": "Madhyapur Thimi Na. Pa."},
    {"id": 286, "districtid": 26, "text": "Suryabinayak Na. Pa."},
    {"id": 287, "districtid": 27, "text": "Budhanilakantha Na. Pa."},
    {"id": 288, "districtid": 27, "text": "Chandragiri Na. Pa."},
    {"id": 289, "districtid": 27, "text": "Dakshinkali Na. Pa."},
    {"id": 290, "districtid": 27, "text": "Gokarneshwor Na. Pa."},
    {"id": 291, "districtid": 27, "text": "Kageshwori Manahora Na. Pa."},
    {"id": 292, "districtid": 27, "text": "Kathmandu Ma. Na. Pa."},
    {"id": 293, "districtid": 27, "text": "Kirtipur Na. Pa."},
    {"id": 294, "districtid": 27, "text": "Nagarjun Na. Pa."},
    {"id": 295, "districtid": 27, "text": "Shankharapur Na. Pa."},
    {"id": 296, "districtid": 27, "text": "Tarakeshwor Na. Pa."},
    {"id": 297, "districtid": 27, "text": "Tokha Na. Pa."},
    {"id": 298, "districtid": 28, "text": "Belkotgadhi Na. Pa."},
    {"id": 299, "districtid": 28, "text": "Bidur Na. Pa."},
    {"id": 300, "districtid": 28, "text": "Dupcheshwar Ga. Pa."},
    {"id": 301, "districtid": 28, "text": "Kakani Ga. Pa."},
    {"id": 302, "districtid": 28, "text": "Kispang Ga. Pa."},
    {"id": 303, "districtid": 28, "text": "Likhu Ga. Pa."},
    {"id": 304, "districtid": 28, "text": "Meghang Ga. Pa."},
    {"id": 305, "districtid": 28, "text": "Panchakanya Ga. Pa."},
    {"id": 306, "districtid": 28, "text": "Shivapuri Ga. Pa."},
    {"id": 307, "districtid": 28, "text": "Suryagadhi Ga. Pa."},
    {"id": 308, "districtid": 28, "text": "Tadi Ga. Pa."},
    {"id": 309, "districtid": 28, "text": "Tarkeshwar Ga. Pa."},
    {"id": 310, "districtid": 29, "text": "Gosaikunda Ga. Pa."},
    {"id": 311, "districtid": 29, "text": "Kalika Ga. Pa."},
    {"id": 312, "districtid": 29, "text": "Naukunda Ga. Pa."},
    {"id": 313, "districtid": 29, "text": "Parbati Kunda Ga. Pa."},
    {"id": 314, "districtid": 29, "text": "Uttargaya Ga. Pa."},
    {"id": 315, "districtid": 30, "text": "Benighat Rorang Ga. Pa."},
    {"id": 316, "districtid": 30, "text": "Dhunibesi Na. Pa."},
    {"id": 317, "districtid": 30, "text": "Gajuri Ga. Pa."},
    {"id": 318, "districtid": 30, "text": "Galchi Ga. Pa."},
    {"id": 319, "districtid": 30, "text": "Gangajamuna Ga. Pa."},
    {"id": 320, "districtid": 30, "text": "Jwalamukhi Ga. Pa."},
    {"id": 321, "districtid": 30, "text": "Khaniyabash Ga. Pa."},
    {"id": 322, "districtid": 30, "text": "Netrawati Dabjong Ga. Pa."},
    {"id": 323, "districtid": 30, "text": "Nilakantha Na. Pa."},
    {"id": 324, "districtid": 30, "text": "Rubi Valley Ga. Pa."},
    {"id": 325, "districtid": 30, "text": "Siddhalek Ga. Pa."},
    {"id": 326, "districtid": 30, "text": "Thakre Ga. Pa."},
    {"id": 327, "districtid": 30, "text": "Tripura Sundari Ga. Pa."},
    {"id": 328, "districtid": 31, "text": "Bagmati Ga. Pa."},
    {"id": 329, "districtid": 31, "text": "Bakaiya Ga. Pa."},
    {"id": 330, "districtid": 31, "text": "Bhimphedi Ga. Pa."},
    {"id": 331, "districtid": 31, "text": "Hetauda Up. Ma. Na. Pa."},
    {"id": 332, "districtid": 31, "text": "Indrasarowar Ga. Pa."},
    {"id": 333, "districtid": 31, "text": "Kailash Ga. Pa."},
    {"id": 334, "districtid": 31, "text": "Makawanpurgadhi Ga. Pa."},
    {"id": 335, "districtid": 31, "text": "Manahari Ga. Pa."},
    {"id": 336, "districtid": 31, "text": "Raksirang Ga. Pa."},
    {"id": 337, "districtid": 31, "text": "Thaha Na. Pa."},
    {"id": 338, "districtid": 32, "text": "Baudhimai Na. Pa."},
    {"id": 339, "districtid": 32, "text": "Brindaban Na. Pa."},
    {"id": 340, "districtid": 32, "text": "Chandrapur Na. Pa."},
    {"id": 341, "districtid": 32, "text": "Dewahhi Gonahi Na. Pa."},
    {"id": 342, "districtid": 32, "text": "Durga Bhagwati Ga. Pa."},
    {"id": 343, "districtid": 32, "text": "Gadhimai Na. Pa."},
    {"id": 344, "districtid": 32, "text": "Garuda Na. Pa."},
    {"id": 345, "districtid": 32, "text": "Gaur Na. Pa."},
    {"id": 346, "districtid": 32, "text": "Gujara Na. Pa."},
    {"id": 347, "districtid": 32, "text": "Ishanath Na. Pa."},
    {"id": 348, "districtid": 32, "text": "Katahariya Na. Pa."},
    {"id": 349, "districtid": 32, "text": "Madhav Narayan Na. Pa."},
    {"id": 350, "districtid": 32, "text": "Maulapur Na. Pa."},
    {"id": 351, "districtid": 32, "text": "Paroha Na. Pa."},
    {"id": 352, "districtid": 32, "text": "Phatuwa Bijayapur Na. Pa."},
    {"id": 353, "districtid": 32, "text": "Rajdevi Na. Pa."},
    {"id": 354, "districtid": 32, "text": "Rajpur Na. Pa."},
    {"id": 355, "districtid": 32, "text": "Yemunamai Ga. Pa."},
    {"id": 356, "districtid": 33, "text": "Adarshkotwal Ga. Pa."},
    {"id": 357, "districtid": 33, "text": "Baragadhi Ga. Pa."},
    {"id": 358, "districtid": 33, "text": "Bishrampur Ga. Pa."},
    {"id": 359, "districtid": 33, "text": "Devtal Ga. Pa."},
    {"id": 360, "districtid": 33, "text": "Jitpur Simara Up. Ma. Na. Pa."},
    {"id": 361, "districtid": 33, "text": "Kalaiya Up. Ma. Na. Pa."},
    {"id": 362, "districtid": 33, "text": "Karaiyamai Ga. Pa."},
    {"id": 363, "districtid": 33, "text": "Kolhabi Na. Pa."},
    {"id": 364, "districtid": 33, "text": "Mahagadhimai Na. Pa."},
    {"id": 365, "districtid": 33, "text": "Nijgadh Na. Pa."},
    {"id": 366, "districtid": 33, "text": "Pacharauta Na. Pa."},
    {"id": 367, "districtid": 33, "text": "Parwanipur Ga. Pa."},
    {"id": 368, "districtid": 33, "text": "Pheta Ga. Pa."},
    {"id": 369, "districtid": 33, "text": "Prasauni Ga. Pa."},
    {"id": 370, "districtid": 33, "text": "Simraungadh Na. Pa."},
    {"id": 371, "districtid": 33, "text": "Suwarna Ga. Pa."},
    {"id": 372, "districtid": 34, "text": "Bahudaramai Na. Pa."},
    {"id": 373, "districtid": 34, "text": "Bindabasini Ga. Pa."},
    {"id": 374, "districtid": 34, "text": "Birgunj Ma. Na. Pa."},
    {"id": 375, "districtid": 34, "text": "Chhipaharmai Ga. Pa."},
    {"id": 376, "districtid": 34, "text": "Dhobini Ga. Pa."},
    {"id": 377, "districtid": 34, "text": "Jagarnathpur Ga. Pa."},
    {"id": 378, "districtid": 34, "text": "Jirabhawani Ga. Pa."},
    {"id": 379, "districtid": 34, "text": "Kalikamai Ga. Pa."},
    {"id": 380, "districtid": 34, "text": "Pakahamainpur Ga. Pa."},
    {"id": 381, "districtid": 34, "text": "Parsagadhi Na. Pa."},
    {"id": 382, "districtid": 34, "text": "Paterwasugauli Ga. Pa."},
    {"id": 383, "districtid": 34, "text": "Pokhariya Na. Pa."},
    {"id": 384, "districtid": 34, "text": "SakhuwaPrasauni Ga. Pa."},
    {"id": 385, "districtid": 34, "text": "Thori Ga. Pa."},
    {"id": 386, "districtid": 35, "text": "Bharatpur Ma. Na. Pa."},
    {"id": 387, "districtid": 35, "text": "Ichchhyakamana Ga. Pa."},
    {"id": 388, "districtid": 35, "text": "Kalika Na. Pa."},
    {"id": 389, "districtid": 35, "text": "Khairahani Na. Pa."},
    {"id": 390, "districtid": 35, "text": "Madi Na. Pa."},
    {"id": 391, "districtid": 35, "text": "Rapti Na. Pa."},
    {"id": 392, "districtid": 35, "text": "Ratnanagar Na. Pa."},
    {"id": 393, "districtid": 36, "text": "Aarughat Ga. Pa."},
    {"id": 394, "districtid": 36, "text": "Ajirkot Ga. Pa."},
    {"id": 395, "districtid": 36, "text": "Bhimsen Ga. Pa."},
    {"id": 396, "districtid": 36, "text": "Chum Nubri Ga. Pa."},
    {"id": 397, "districtid": 36, "text": "Dharche Ga. Pa."},
    {"id": 398, "districtid": 36, "text": "Gandaki Ga. Pa."},
    {"id": 399, "districtid": 36, "text": "Gorkha Na. Pa."},
    {"id": 400, "districtid": 36, "text": "Palungtar Na. Pa."},
    {"id": 401, "districtid": 36, "text": "Sahid Lakhan Ga. Pa."},
    {"id": 402, "districtid": 36, "text": "Siranchok Ga. Pa."},
    {"id": 403, "districtid": 36, "text": "Sulikot Ga. Pa."},
    {"id": 404, "districtid": 37, "text": "Besishahar Na. Pa."},
    {"id": 405, "districtid": 37, "text": "Dordi Ga. Pa."},
    {"id": 406, "districtid": 37, "text": "Dudhpokhari Ga. Pa."},
    {"id": 407, "districtid": 37, "text": "Kwholasothar Ga. Pa."},
    {"id": 408, "districtid": 37, "text": "MadhyaNepal Na. Pa."},
    {"id": 409, "districtid": 37, "text": "Marsyangdi Ga. Pa."},
    {"id": 410, "districtid": 37, "text": "Rainas Na. Pa."},
    {"id": 411, "districtid": 37, "text": "Sundarbazar Na. Pa."},
    {"id": 412, "districtid": 38, "text": "Anbukhaireni Ga. Pa."},
    {"id": 413, "districtid": 38, "text": "Bandipur Ga. Pa."},
    {"id": 414, "districtid": 38, "text": "Bhanu Na. Pa."},
    {"id": 415, "districtid": 38, "text": "Bhimad Na. Pa."},
    {"id": 416, "districtid": 38, "text": "Byas Na. Pa."},
    {"id": 417, "districtid": 38, "text": "Devghat Ga. Pa."},
    {"id": 418, "districtid": 38, "text": "Ghiring Ga. Pa."},
    {"id": 419, "districtid": 38, "text": "Myagde Ga. Pa."},
    {"id": 420, "districtid": 38, "text": "Rhishing Ga. Pa."},
    {"id": 421, "districtid": 38, "text": "Shuklagandaki Na. Pa."},
    {"id": 422, "districtid": 39, "text": "Aandhikhola Ga. Pa."},
    {"id": 423, "districtid": 39, "text": "Arjunchaupari Ga. Pa."},
    {"id": 424, "districtid": 39, "text": "Bhirkot Na. Pa."},
    {"id": 425, "districtid": 39, "text": "Biruwa Ga. Pa."},
    {"id": 426, "districtid": 39, "text": "Chapakot Na. Pa."},
    {"id": 427, "districtid": 39, "text": "Galyang Na. Pa."},
    {"id": 428, "districtid": 39, "text": "Harinas Ga. Pa."},
    {"id": 429, "districtid": 39, "text": "Kaligandagi Ga. Pa."},
    {"id": 430, "districtid": 39, "text": "Phedikhola Ga. Pa."},
    {"id": 431, "districtid": 39, "text": "Putalibazar Na. Pa."},
    {"id": 432, "districtid": 39, "text": "Waling Na. Pa."},
    {"id": 433, "districtid": 40, "text": "Annapurna Ga. Pa."},
    {"id": 434, "districtid": 40, "text": "Machhapuchchhre Ga. Pa."},
    {"id": 435, "districtid": 40, "text": "Madi Ga. Pa."},
    {"id": 436, "districtid": 40, "text": "Pokhara Lekhnath Ma. Na. Pa."},
    {"id": 437, "districtid": 40, "text": "Rupa Ga. Pa."},
    {"id": 438, "districtid": 41, "text": "Chame Ga. Pa."},
    {"id": 439, "districtid": 41, "text": "Narphu Ga. Pa."},
    {"id": 440, "districtid": 41, "text": "Nashong Ga. Pa."},
    {"id": 441, "districtid": 41, "text": "Neshyang Ga. Pa."},
    {"id": 442, "districtid": 42, "text": "Barhagaun Muktikhsetra Ga. Pa."},
    {"id": 443, "districtid": 42, "text": "Dalome Ga. Pa."},
    {"id": 444, "districtid": 42, "text": "Gharapjhong Ga. Pa."},
    {"id": 445, "districtid": 42, "text": "Lomanthang Ga. Pa."},
    {"id": 446, "districtid": 42, "text": "Thasang Ga. Pa."},
    {"id": 447, "districtid": 43, "text": "Bihadi Ga. Pa."},
    {"id": 448, "districtid": 43, "text": "Jaljala Ga. Pa."},
    {"id": 449, "districtid": 43, "text": "Kushma Na. Pa."},
    {"id": 450, "districtid": 43, "text": "Mahashila Ga. Pa."},
    {"id": 451, "districtid": 43, "text": "Modi Ga. Pa."},
    {"id": 452, "districtid": 43, "text": "Painyu Ga. Pa."},
    {"id": 453, "districtid": 43, "text": "Phalebas Na. Pa."},
    {"id": 454, "districtid": 44, "text": "Annapurna Ga. Pa."},
    {"id": 455, "districtid": 44, "text": "Beni Na. Pa."},
    {"id": 456, "districtid": 44, "text": "Dhaulagiri Ga. Pa."},
    {"id": 457, "districtid": 44, "text": "Malika Ga. Pa."},
    {"id": 458, "districtid": 44, "text": "Mangala Ga. Pa."},
    {"id": 459, "districtid": 44, "text": "Raghuganga Ga. Pa."},
    {"id": 460, "districtid": 45, "text": "Badigad Ga. Pa."},
    {"id": 461, "districtid": 45, "text": "Baglung Na. Pa."},
    {"id": 462, "districtid": 45, "text": "Bareng Ga. Pa."},
    {"id": 463, "districtid": 45, "text": "Dhorpatan Na. Pa."},
    {"id": 464, "districtid": 45, "text": "Galkot Na. Pa."},
    {"id": 465, "districtid": 45, "text": "Jaimuni Na. Pa."},
    {"id": 466, "districtid": 45, "text": "Kanthekhola Ga. Pa."},
    {"id": 467, "districtid": 45, "text": "Nisikhola Ga. Pa."},
    {"id": 468, "districtid": 45, "text": "Taman Khola Ga. Pa."},
    {"id": 469, "districtid": 45, "text": "Tara Khola Ga. Pa."},
    {"id": 470, "districtid": 46, "text": "Chandrakot Ga. Pa."},
    {"id": 471, "districtid": 46, "text": "Chatrakot Ga. Pa."},
    {"id": 472, "districtid": 46, "text": "Dhurkot Ga. Pa."},
    {"id": 473, "districtid": 46, "text": "Gulmidarbar Ga. Pa."},
    {"id": 474, "districtid": 46, "text": "Isma Ga. Pa."},
    {"id": 475, "districtid": 46, "text": "Kaligandaki Ga. Pa."},
    {"id": 476, "districtid": 46, "text": "Madane Ga. Pa."},
    {"id": 477, "districtid": 46, "text": "Malika Ga. Pa."},
    {"id": 478, "districtid": 46, "text": "Musikot Na. Pa."},
    {"id": 479, "districtid": 46, "text": "Resunga Na. Pa."},
    {"id": 480, "districtid": 46, "text": "Ruru Ga. Pa."},
    {"id": 481, "districtid": 46, "text": "Satyawati Ga. Pa."},
    {"id": 482, "districtid": 47, "text": "Bagnaskali Ga. Pa."},
    {"id": 483, "districtid": 47, "text": "Mathagadhi Ga. Pa."},
    {"id": 484, "districtid": 47, "text": "Nisdi Ga. Pa."},
    {"id": 485, "districtid": 47, "text": "Purbakhola Ga. Pa."},
    {"id": 486, "districtid": 47, "text": "Rainadevi Chhahara Ga. Pa."},
    {"id": 487, "districtid": 47, "text": "Rambha Ga. Pa."},
    {"id": 488, "districtid": 47, "text": "Rampur Na. Pa."},
    {"id": 489, "districtid": 47, "text": "Ribdikot Ga. Pa."},
    {"id": 490, "districtid": 47, "text": "Tansen Na. Pa."},
    {"id": 491, "districtid": 47, "text": "Tinau Ga. Pa."},
    {"id": 492, "districtid": 48, "text": "Bardaghat Na. Pa."},
    {"id": 493, "districtid": 48, "text": "Palhi Nandan Ga. Pa."},
    {"id": 494, "districtid": 48, "text": "Pratappur Ga. Pa."},
    {"id": 495, "districtid": 48, "text": "Ramgram Na. Pa."},
    {"id": 496, "districtid": 48, "text": "Sarawal Ga. Pa."},
    {"id": 497, "districtid": 48, "text": "Sunwal Na. Pa."},
    {"id": 498, "districtid": 48, "text": "Susta Ga. Pa."},
    {"id": 499, "districtid": 49, "text": "Binayee Tribeni Ga. Pa."},
    {"id": 500, "districtid": 49, "text": "Bulingtar Ga. Pa."},
    {"id": 501, "districtid": 49, "text": "Bungdikali Ga. Pa."},
    {"id": 502, "districtid": 49, "text": "Devchuli Na. Pa."},
    {"id": 503, "districtid": 49, "text": "Gaidakot Na. Pa."},
    {"id": 504, "districtid": 49, "text": "Hupsekot Ga. Pa."},
    {"id": 505, "districtid": 49, "text": "Kawasoti Na. Pa."},
    {"id": 506, "districtid": 49, "text": "Madhyabindu Na. Pa."},
    {"id": 507, "districtid": 50, "text": "Butwal Up. Ma. Na. Pa."},
    {"id": 508, "districtid": 50, "text": "Devdaha Na. Pa."},
    {"id": 509, "districtid": 50, "text": "Gaidahawa Ga. Pa."},
    {"id": 510, "districtid": 50, "text": "Kanchan Ga. Pa."},
    {"id": 511, "districtid": 50, "text": "Kotahimai Ga. Pa."},
    {"id": 512, "districtid": 50, "text": "Lumbini Sanskritik Na. Pa."},
    {"id": 513, "districtid": 50, "text": "Marchawari Ga. Pa."},
    {"id": 514, "districtid": 50, "text": "Mayadevi Ga. Pa."},
    {"id": 515, "districtid": 50, "text": "Omsatiya Ga. Pa."},
    {"id": 516, "districtid": 50, "text": "Rohini Ga. Pa."},
    {"id": 517, "districtid": 50, "text": "Sainamaina Na. Pa."},
    {"id": 518, "districtid": 50, "text": "Sammarimai Ga. Pa."},
    {"id": 519, "districtid": 50, "text": "Siddharthanagar Na. Pa."},
    {"id": 520, "districtid": 50, "text": "Siyari Ga. Pa."},
    {"id": 521, "districtid": 50, "text": "Sudhdhodhan Ga. Pa."},
    {"id": 522, "districtid": 50, "text": "Tillotama Na. Pa."},
    {"id": 523, "districtid": 51, "text": "Bhumekasthan Na. Pa."},
    {"id": 524, "districtid": 51, "text": "Chhatradev Ga. Pa."},
    {"id": 525, "districtid": 51, "text": "Malarani Ga. Pa."},
    {"id": 526, "districtid": 51, "text": "Panini Ga. Pa."},
    {"id": 527, "districtid": 51, "text": "Sandhikharka Na. Pa."},
    {"id": 528, "districtid": 51, "text": "Sitganga Na. Pa."},
    {"id": 529, "districtid": 52, "text": "Banganga Na. Pa."},
    {"id": 530, "districtid": 52, "text": "Bijayanagar Ga. Pa."},
    {"id": 531, "districtid": 52, "text": "Buddhabhumi Na. Pa."},
    {"id": 532, "districtid": 52, "text": "Kapilbastu Na. Pa."},
    {"id": 533, "districtid": 52, "text": "Krishnanagar Na. Pa."},
    {"id": 534, "districtid": 52, "text": "Maharajgunj Na. Pa."},
    {"id": 535, "districtid": 52, "text": "Mayadevi Ga. Pa."},
    {"id": 536, "districtid": 52, "text": "Shivaraj Na. Pa."},
    {"id": 537, "districtid": 52, "text": "Suddhodhan Ga. Pa."},
    {"id": 538, "districtid": 52, "text": "Yashodhara Ga. Pa."},
    {"id": 539, "districtid": 53, "text": "Ayirabati Ga. Pa."},
    {"id": 540, "districtid": 53, "text": "Gaumukhi Ga. Pa."},
    {"id": 541, "districtid": 53, "text": "Jhimruk Ga. Pa."},
    {"id": 542, "districtid": 53, "text": "Mallarani Ga. Pa."},
    {"id": 543, "districtid": 53, "text": "Mandavi Ga. Pa."},
    {"id": 544, "districtid": 53, "text": "Naubahini Ga. Pa."},
    {"id": 545, "districtid": 53, "text": "Pyuthan Na. Pa."},
    {"id": 546, "districtid": 53, "text": "Sarumarani Ga. Pa."},
    {"id": 547, "districtid": 53, "text": "Sworgadwary Na. Pa."},
    {"id": 548, "districtid": 54, "text": "Duikholi Ga. Pa."},
    {"id": 549, "districtid": 54, "text": "Lungri Ga. Pa."},
    {"id": 550, "districtid": 54, "text": "Madi Ga. Pa."},
    {"id": 551, "districtid": 54, "text": "Rolpa Na. Pa."},
    {"id": 552, "districtid": 54, "text": "Runtigadi Ga. Pa."},
    {"id": 553, "districtid": 54, "text": "Sukidaha Ga. Pa."},
    {"id": 554, "districtid": 54, "text": "Sunchhahari Ga. Pa."},
    {"id": 555, "districtid": 54, "text": "Suwarnabati Ga. Pa."},
    {"id": 556, "districtid": 54, "text": "Thawang Ga. Pa."},
    {"id": 557, "districtid": 54, "text": "Tribeni Ga. Pa."},
    {"id": 558, "districtid": 55, "text": "Aathbiskot Na. Pa."},
    {"id": 559, "districtid": 55, "text": "Banfikot Ga. Pa."},
    {"id": 560, "districtid": 55, "text": "Chaurjahari Na. Pa."},
    {"id": 561, "districtid": 55, "text": "Musikot Na. Pa."},
    {"id": 562, "districtid": 55, "text": "Sani Bheri Ga. Pa."},
    {"id": 563, "districtid": 55, "text": "Tribeni Ga. Pa."},
    {"id": 564, "districtid": 56, "text": "Bhume Ga. Pa."},
    {"id": 565, "districtid": 56, "text": "Putha Uttarganga Ga. Pa."},
    {"id": 566, "districtid": 56, "text": "Sisne Ga. Pa."},
    {"id": 567, "districtid": 57, "text": "Bagchaur Na. Pa."},
    {"id": 568, "districtid": 57, "text": "Bangad Kupinde Na. Pa."},
    {"id": 569, "districtid": 57, "text": "Chhatreshwori Ga. Pa."},
    {"id": 570, "districtid": 57, "text": "Darma Ga. Pa."},
    {"id": 571, "districtid": 57, "text": "Dhorchaur Ga. Pa."},
    {"id": 572, "districtid": 57, "text": "Kalimati Ga. Pa."},
    {"id": 573, "districtid": 57, "text": "Kapurkot Ga. Pa."},
    {"id": 574, "districtid": 57, "text": "Kumakhmalika Ga. Pa."},
    {"id": 575, "districtid": 57, "text": "Sharada Na. Pa."},
    {"id": 576, "districtid": 57, "text": "Tribeni Ga. Pa."},
    {"id": 577, "districtid": 58, "text": "Babai Ga. Pa."},
    {"id": 578, "districtid": 58, "text": "Banglachuli Ga. Pa."},
    {"id": 579, "districtid": 58, "text": "Dangisharan Ga. Pa."},
    {"id": 580, "districtid": 58, "text": "Gadhawa Ga. Pa."},
    {"id": 581, "districtid": 58, "text": "Ghorahi Up. Ma. Na. Pa."},
    {"id": 582, "districtid": 58, "text": "Lamahi Na. Pa."},
    {"id": 583, "districtid": 58, "text": "Rajpur Ga. Pa."},
    {"id": 584, "districtid": 58, "text": "Rapti Ga. Pa."},
    {"id": 585, "districtid": 58, "text": "Shantinagar Ga. Pa."},
    {"id": 586, "districtid": 58, "text": "Tulsipur Up. Ma. Na. Pa."},
    {"id": 587, "districtid": 59, "text": "Badhaiyatal Ga. Pa."},
    {"id": 588, "districtid": 59, "text": "Bansagadhi Na. Pa."},
    {"id": 589, "districtid": 59, "text": "Barbardiya Na. Pa."},
    {"id": 590, "districtid": 59, "text": "Geruwa Ga. Pa."},
    {"id": 591, "districtid": 59, "text": "Gulariya Na. Pa."},
    {"id": 592, "districtid": 59, "text": "Madhuwan Na. Pa."},
    {"id": 593, "districtid": 59, "text": "Rajapur Na. Pa."},
    {"id": 594, "districtid": 59, "text": "Thakurbaba Na. Pa."},
    {"id": 595, "districtid": 60, "text": "Barahtal Ga. Pa."},
    {"id": 596, "districtid": 60, "text": "Bheriganga Na. Pa."},
    {"id": 597, "districtid": 60, "text": "Birendranagar Na. Pa."},
    {"id": 598, "districtid": 60, "text": "Chaukune Ga. Pa."},
    {"id": 599, "districtid": 60, "text": "Chingad Ga. Pa."},
    {"id": 600, "districtid": 60, "text": "Gurbhakot Na. Pa."},
    {"id": 601, "districtid": 60, "text": "Lekbeshi Na. Pa."},
    {"id": 602, "districtid": 60, "text": "Panchpuri Na. Pa."},
    {"id": 603, "districtid": 60, "text": "Simta Ga. Pa."},
    {"id": 604, "districtid": 61, "text": "Aathabis Na. Pa."},
    {"id": 605, "districtid": 61, "text": "Bhagawatimai Ga. Pa."},
    {"id": 606, "districtid": 61, "text": "Bhairabi Ga. Pa."},
    {"id": 607, "districtid": 61, "text": "Chamunda Bindrasaini Na. Pa."},
    {"id": 608, "districtid": 61, "text": "Dullu Na. Pa."},
    {"id": 609, "districtid": 61, "text": "Dungeshwor Ga. Pa."},
    {"id": 610, "districtid": 61, "text": "Gurans Ga. Pa."},
    {"id": 611, "districtid": 61, "text": "Mahabu Ga. Pa."},
    {"id": 612, "districtid": 61, "text": "Narayan Na. Pa."},
    {"id": 613, "districtid": 61, "text": "Naumule Ga. Pa."},
    {"id": 614, "districtid": 61, "text": "Thantikandh Ga. Pa."},
    {"id": 615, "districtid": 62, "text": "Baijanath Ga. Pa."},
    {"id": 616, "districtid": 62, "text": "Duduwa Ga. Pa."},
    {"id": 617, "districtid": 62, "text": "Janki Ga. Pa."},
    {"id": 618, "districtid": 62, "text": "Khajura Ga. Pa."},
    {"id": 619, "districtid": 62, "text": "Kohalpur Na. Pa."},
    {"id": 620, "districtid": 62, "text": "Narainapur Ga. Pa."},
    {"id": 621, "districtid": 62, "text": "Nepalgunj Up. Ma. Na. Pa."},
    {"id": 622, "districtid": 62, "text": "Rapti Sonari Ga. Pa."},
    {"id": 623, "districtid": 63, "text": "Barekot Ga. Pa."},
    {"id": 624, "districtid": 63, "text": "Bheri Na. Pa."},
    {"id": 625, "districtid": 63, "text": "Chhedagad Na. Pa."},
    {"id": 626, "districtid": 63, "text": "Junichande Ga. Pa."},
    {"id": 627, "districtid": 63, "text": "Kuse Ga. Pa."},
    {"id": 628, "districtid": 63, "text": "Shiwalaya Ga. Pa."},
    {"id": 629, "districtid": 63, "text": "Tribeni Nalagad Na. Pa."},
    {"id": 630, "districtid": 64, "text": "Chharka Tangsong Ga. Pa."},
    {"id": 631, "districtid": 64, "text": "Dolpo Buddha Ga. Pa."},
    {"id": 632, "districtid": 64, "text": "Jagadulla Ga. Pa."},
    {"id": 633, "districtid": 64, "text": "Kaike Ga. Pa."},
    {"id": 634, "districtid": 64, "text": "Mudkechula Ga. Pa."},
    {"id": 635, "districtid": 64, "text": "Shey Phoksundo Ga. Pa."},
    {"id": 636, "districtid": 64, "text": "Thuli Bheri Na. Pa."},
    {"id": 637, "districtid": 64, "text": "Tripurasundari Na. Pa."},
    {"id": 638, "districtid": 65, "text": "Adanchuli Ga. Pa."},
    {"id": 639, "districtid": 65, "text": "Chankheli Ga. Pa."},
    {"id": 640, "districtid": 65, "text": "Kharpunath Ga. Pa."},
    {"id": 641, "districtid": 65, "text": "Namkha Ga. Pa."},
    {"id": 642, "districtid": 65, "text": "Sarkegad Ga. Pa."},
    {"id": 643, "districtid": 65, "text": "Simkot Ga. Pa."},
    {"id": 644, "districtid": 65, "text": "Tanjakot Ga. Pa."},
    {"id": 645, "districtid": 66, "text": "Subh Kalika Ga. Pa."},
    {"id": 646, "districtid": 66, "text": "Khandachakra Na. Pa."},
    {"id": 647, "districtid": 66, "text": "Mahawai Ga. Pa."},
    {"id": 648, "districtid": 66, "text": "Naraharinath Ga. Pa."},
    {"id": 649, "districtid": 66, "text": "Pachaljharana Ga. Pa."},
    {"id": 650, "districtid": 66, "text": "Palata Ga. Pa."},
    {"id": 651, "districtid": 66, "text": "Raskot Na. Pa."},
    {"id": 652, "districtid": 66, "text": "Sanni Tribeni Ga. Pa."},
    {"id": 653, "districtid": 66, "text": "Tilagufa Na. Pa."},
    {"id": 654, "districtid": 67, "text": "Chhayanath Rara Na. Pa."},
    {"id": 655, "districtid": 67, "text": "Khatyad Ga. Pa."},
    {"id": 656, "districtid": 67, "text": "Mugum Karmarong Ga. Pa."},
    {"id": 657, "districtid": 67, "text": "Soru Ga. Pa."},
    {"id": 658, "districtid": 68, "text": "Chandannath Na. Pa."},
    {"id": 659, "districtid": 68, "text": "Guthichaur Ga. Pa."},
    {"id": 660, "districtid": 68, "text": "Hima Ga. Pa."},
    {"id": 661, "districtid": 68, "text": "Kanakasundari Ga. Pa."},
    {"id": 662, "districtid": 68, "text": "Patrasi Ga. Pa."},
    {"id": 663, "districtid": 68, "text": "Sinja Ga. Pa."},
    {"id": 664, "districtid": 68, "text": "Tatopani Ga. Pa."},
    {"id": 665, "districtid": 68, "text": "Tila Ga. Pa."},
    {"id": 666, "districtid": 69, "text": "Badimalika Na. Pa."},
    {"id": 667, "districtid": 69, "text": "Budhiganga Na. Pa."},
    {"id": 668, "districtid": 69, "text": "Budhinanda Na. Pa."},
    {"id": 669, "districtid": 69, "text": "Chhededaha Ga. Pa."},
    {"id": 670, "districtid": 69, "text": "Gaumul Ga. Pa."},
    {"id": 671, "districtid": 69, "text": "Himali Ga. Pa."},
    {"id": 672, "districtid": 69, "text": "Pandav Gupha Ga. Pa."},
    {"id": 673, "districtid": 69, "text": "Swami Kartik Ga. Pa."},
    {"id": 674, "districtid": 69, "text": "Tribeni Na. Pa."},
    {"id": 675, "districtid": 70, "text": "Bithadchir Ga. Pa."},
    {"id": 676, "districtid": 70, "text": "Bungal Na. Pa."},
    {"id": 677, "districtid": 70, "text": "Chabispathivera Ga. Pa."},
    {"id": 678, "districtid": 70, "text": "Durgathali Ga. Pa."},
    {"id": 679, "districtid": 70, "text": "JayaPrithivi Na. Pa."},
    {"id": 680, "districtid": 70, "text": "Kanda Ga. Pa."},
    {"id": 681, "districtid": 70, "text": "Kedarseu Ga. Pa."},
    {"id": 682, "districtid": 70, "text": "Khaptadchhanna Ga. Pa."},
    {"id": 683, "districtid": 70, "text": "Masta Ga. Pa."},
    {"id": 684, "districtid": 70, "text": "Surma Ga. Pa."},
    {"id": 685, "districtid": 70, "text": "Talkot Ga. Pa."},
    {"id": 686, "districtid": 70, "text": "Thalara Ga. Pa."},
    {"id": 687, "districtid": 71, "text": "Bannigadhi Jayagadh Ga. Pa."},
    {"id": 688, "districtid": 71, "text": "Chaurpati Ga. Pa."},
    {"id": 689, "districtid": 71, "text": "Dhakari Ga. Pa."},
    {"id": 690, "districtid": 71, "text": "Kamalbazar Na. Pa."},
    {"id": 691, "districtid": 71, "text": "Mangalsen Na. Pa."},
    {"id": 692, "districtid": 71, "text": "Mellekh Ga. Pa."},
    {"id": 693, "districtid": 71, "text": "Panchadewal Binayak Na. Pa."},
    {"id": 694, "districtid": 71, "text": "Ramaroshan Ga. Pa."},
    {"id": 695, "districtid": 71, "text": "Sanphebagar Na. Pa."},
    {"id": 696, "districtid": 71, "text": "Turmakhad Ga. Pa."},
    {"id": 697, "districtid": 72, "text": "Adharsha Ga. Pa."},
    {"id": 698, "districtid": 72, "text": "Badikedar Ga. Pa."},
    {"id": 699, "districtid": 72, "text": "Bogtan Ga. Pa."},
    {"id": 700, "districtid": 72, "text": "Dipayal Silgadi Na. Pa."},
    {"id": 701, "districtid": 72, "text": "Jorayal Ga. Pa."},
    {"id": 702, "districtid": 72, "text": "K I Singh Ga. Pa."},
    {"id": 703, "districtid": 72, "text": "Purbichauki Ga. Pa."},
    {"id": 704, "districtid": 72, "text": "Sayal Ga. Pa."},
    {"id": 705, "districtid": 72, "text": "Shikhar Na. Pa."},
    {"id": 706, "districtid": 73, "text": "Bardagoriya Ga. Pa."},
    {"id": 707, "districtid": 73, "text": "Bhajani Na. Pa."},
    {"id": 708, "districtid": 73, "text": "Chure Ga. Pa."},
    {"id": 709, "districtid": 73, "text": "Dhangadhi Up. Ma. Na. Pa."},
    {"id": 710, "districtid": 73, "text": "Gauriganga Na. Pa."},
    {"id": 711, "districtid": 73, "text": "Ghodaghodi Na. Pa."},
    {"id": 712, "districtid": 73, "text": "Godawari Na. Pa."},
    {"id": 713, "districtid": 73, "text": "Janaki Ga. Pa."},
    {"id": 714, "districtid": 73, "text": "Joshipur Ga. Pa."},
    {"id": 715, "districtid": 73, "text": "Kailari Ga. Pa."},
    {"id": 716, "districtid": 73, "text": "Lamkichuha Na. Pa."},
    {"id": 717, "districtid": 73, "text": "Mohanyal Ga. Pa."},
    {"id": 718, "districtid": 73, "text": "Tikapur Na. Pa."},
    {"id": 719, "districtid": 74, "text": "Bedkot Na. Pa."},
    {"id": 720, "districtid": 74, "text": "Belauri Na. Pa."},
    {"id": 721, "districtid": 74, "text": "Beldandi Ga. Pa."},
    {"id": 722, "districtid": 74, "text": "Bhimdatta Na. Pa."},
    {"id": 723, "districtid": 74, "text": "Krishnapur Na. Pa."},
    {"id": 724, "districtid": 74, "text": "Laljhadi Ga. Pa."},
    {"id": 725, "districtid": 74, "text": "Mahakali Na. Pa."},
    {"id": 726, "districtid": 74, "text": "Punarbas Na. Pa."},
    {"id": 727, "districtid": 74, "text": "Shuklaphanta Na. Pa."},
    {"id": 728, "districtid": 75, "text": "Ajaymeru Ga. Pa."},
    {"id": 729, "districtid": 75, "text": "Alital Ga. Pa."},
    {"id": 730, "districtid": 75, "text": "Amargadhi Na. Pa."},
    {"id": 731, "districtid": 75, "text": "Bhageshwar Ga. Pa."},
    {"id": 732, "districtid": 75, "text": "Ganayapdhura Ga. Pa."},
    {"id": 733, "districtid": 75, "text": "Nawadurga Ga. Pa."},
    {"id": 734, "districtid": 75, "text": "Parashuram Na. Pa."},
    {"id": 735, "districtid": 76, "text": "Dasharathchanda Na. Pa."},
    {"id": 736, "districtid": 76, "text": "Dilasaini Ga. Pa."},
    {"id": 737, "districtid": 76, "text": "Dogadakedar Ga. Pa."},
    {"id": 738, "districtid": 76, "text": "Melauli Na. Pa."},
    {"id": 739, "districtid": 76, "text": "Pancheshwar Ga. Pa."},
    {"id": 740, "districtid": 76, "text": "Patan Na. Pa."},
    {"id": 741, "districtid": 76, "text": "Purchaudi Na. Pa."},
    {"id": 742, "districtid": 76, "text": "Shivanath Ga. Pa."},
    {"id": 743, "districtid": 76, "text": "Sigas Ga. Pa."},
    {"id": 744, "districtid": 76, "text": "Surnaya Ga. Pa."},
    {"id": 745, "districtid": 77, "text": "Apihimal Ga. Pa."},
    {"id": 746, "districtid": 77, "text": "Byas Ga. Pa."},
    {"id": 747, "districtid": 77, "text": "Dunhu Ga. Pa."},
    {"id": 748, "districtid": 77, "text": "Lekam Ga. Pa."},
    {"id": 749, "districtid": 77, "text": "Mahakali Na. Pa."},
    {"id": 750, "districtid": 77, "text": "Malikaarjun Ga. Pa."},
    {"id": 751, "districtid": 77, "text": "Marma Ga. Pa."},
    {"id": 752, "districtid": 77, "text": "Naugad Ga. Pa."},
    {"id": 753, "districtid": 77, "text": "Shailyashikhar Na. Pa."}
  ]
};
