var nepalJson = {
  "province": [
    {"id": 1, "text": "Province No.1", "textNP": "प्रदेश नंबर १"},
    {"id": 2, "text": "Madhesh Province", "textNP": "मधेश प्रदेश"},
    {"id": 3, "text": "Bagmati Province", "textNP": "बाग्मती प्रदेश"},
    {"id": 4, "text": "Gandaki Province", "textNP": "गण्डकी प्रदेश"},
    {"id": 5, "text": "Lumbini Provience", "textNP": "लुम्बिनी प्रदेश"},
    {"id": 6, "text": "Karnali Province", "textNP": "कर्णाली प्रदेश"},
    {"id": 7, "text": "Sudur Paschim Province", "textNP": "सुदूर पश्चिम प्रदेश"}
  ],
  "zone": [
    {"id": 1, "text": "Mechi", "textNP": "मेची"},
    {"id": 2, "text": "Koshi", "textNP": "कोशी"},
    {"id": 3, "text": "Sagarmatha", "textNP": "सगरमाथा"},
    {"id": 4, "text": "Janakpur", "textNP": "जनकपुर"},
    {"id": 5, "text": "Bagmati", "textNP": "बागमति"},
    {"id": 6, "text": "Narayani", "textNP": "नारायणी"},
    {"id": 7, "text": "Gandaki", "textNP": "गण्डकी"},
    {"id": 8, "text": "Dhawalagiri", "textNP": "धवलागिरी"},
    {"id": 9, "text": "Lumbini", "textNP": "लुम्विनी"},
    {"id": 10, "text": "Rapti", "textNP": "राप्ती"},
    {"id": 11, "text": "Bheri", "textNP": "भेरी"},
    {"id": 12, "text": "Karnali", "textNP": "कर्णाली"},
    {"id": 13, "text": "Seti", "textNP": "सेती"},
    {"id": 14, "text": "Mahakali", "textNP": "महाकाली"}
  ],
  "district": [
    {
      "id": 1,
      "zoneid": 1,
      "stateid": 1,
      "text": "Taplejung",
      "textNP": "ताप्लेजुंग "
    },
    {
      "id": 2,
      "zoneid": 1,
      "stateid": 1,
      "text": "Panchthar",
      "textNP": "पांचथर "
    },
    {"id": 3, "zoneid": 1, "stateid": 1, "text": "Ilam", "textNP": "इलाम "},
    {"id": 4, "zoneid": 1, "stateid": 1, "text": "Jhapa", "textNP": "झापा "},
    {"id": 5, "zoneid": 2, "stateid": 1, "text": "Morang", "textNP": "मोरंग "},
    {"id": 6, "zoneid": 2, "stateid": 1, "text": "Sunsari", "textNP": "सुनसरी"},
    {
      "id": 7,
      "zoneid": 2,
      "stateid": 1,
      "text": "Dhankutta",
      "textNP": "धनकुटा "
    },
    {
      "id": 8,
      "zoneid": 2,
      "stateid": 1,
      "text": "Sankhuwasabha",
      "textNP": "संखुवासभा "
    },
    {
      "id": 9,
      "zoneid": 2,
      "stateid": 1,
      "text": "Bhojpur",
      "textNP": "भोजपुर "
    },
    {
      "id": 10,
      "zoneid": 2,
      "stateid": 1,
      "text": "Terhathum",
      "textNP": "तेह्रथुम "
    },
    {
      "id": 11,
      "zoneid": 3,
      "stateid": 1,
      "text": "Okhaldunga",
      "textNP": "ओखलढुंगा "
    },
    {
      "id": 12,
      "zoneid": 3,
      "stateid": 1,
      "text": "Khotang",
      "textNP": "खोटाँग "
    },
    {
      "id": 13,
      "zoneid": 3,
      "stateid": 1,
      "text": "Solukhumbu",
      "textNP": "सोलुखुम्बू "
    },
    {
      "id": 14,
      "zoneid": 3,
      "stateid": 1,
      "text": "Udaypur",
      "textNP": "उदयपुर "
    },
    {
      "id": 15,
      "zoneid": 3,
      "stateid": 2,
      "text": "Saptari",
      "textNP": "सप्तरी "
    },
    {
      "id": 16,
      "zoneid": 3,
      "stateid": 2,
      "text": "Siraha",
      "textNP": "सिराहा "
    },
    {
      "id": 17,
      "zoneid": 4,
      "stateid": 2,
      "text": "Dhanusa",
      "textNP": "धनुषा "
    },
    {
      "id": 18,
      "zoneid": 4,
      "stateid": 2,
      "text": "Mahottari",
      "textNP": "महोत्तरी "
    },
    {
      "id": 19,
      "zoneid": 4,
      "stateid": 2,
      "text": "Sarlahi",
      "textNP": "सर्लाही "
    },
    {
      "id": 20,
      "zoneid": 4,
      "stateid": 3,
      "text": "Sindhuli",
      "textNP": "सिन्धुली "
    },
    {
      "id": 21,
      "zoneid": 4,
      "stateid": 3,
      "text": "Ramechhap",
      "textNP": "रामेछाप "
    },
    {"id": 22, "zoneid": 4, "stateid": 3, "text": "Dolkha", "textNP": "दोलखा"},
    {
      "id": 23,
      "zoneid": 5,
      "stateid": 3,
      "text": "Sindhupalchauk",
      "textNP": "सिन्धुपाल्चोक "
    },
    {
      "id": 24,
      "zoneid": 5,
      "stateid": 3,
      "text": "Kavreplanchauk",
      "textNP": "काभ्रेपलान्चोक "
    },
    {
      "id": 25,
      "zoneid": 5,
      "stateid": 3,
      "text": "Lalitpur",
      "textNP": "ललितपुर "
    },
    {
      "id": 26,
      "zoneid": 5,
      "stateid": 3,
      "text": "Bhaktapur",
      "textNP": "भक्तपुर "
    },
    {
      "id": 27,
      "zoneid": 5,
      "stateid": 3,
      "text": "Kathmandu",
      "textNP": "काठमाडौँ "
    },
    {
      "id": 28,
      "zoneid": 5,
      "stateid": 3,
      "text": "Nuwakot",
      "textNP": "नुवाकोट "
    },
    {"id": 29, "zoneid": 5, "stateid": 3, "text": "Rasuwa", "textNP": "रसुवा "},
    {"id": 30, "zoneid": 5, "stateid": 3, "text": "Dhading", "textNP": "धादिङ"},
    {
      "id": 31,
      "zoneid": 6,
      "stateid": 3,
      "text": "Makwanpur",
      "textNP": "मकवानपुर "
    },
    {
      "id": 32,
      "zoneid": 6,
      "stateid": 2,
      "text": "Rauthat",
      "textNP": "रौतहट "
    },
    {"id": 33, "zoneid": 6, "stateid": 2, "text": "Bara", "textNP": "बारा "},
    {"id": 34, "zoneid": 6, "stateid": 2, "text": "Parsa", "textNP": "पर्सा "},
    {"id": 35, "zoneid": 6, "stateid": 3, "text": "Chitwan", "textNP": "चितवन"},
    {"id": 36, "zoneid": 7, "stateid": 4, "text": "Gorkha", "textNP": "गोरखा "},
    {
      "id": 37,
      "zoneid": 7,
      "stateid": 4,
      "text": "Lamjung",
      "textNP": "लमजुङ "
    },
    {
      "id": 38,
      "zoneid": 7,
      "stateid": 4,
      "text": "Tanahun",
      "textNP": "तनहुँ "
    },
    {
      "id": 39,
      "zoneid": 7,
      "stateid": 4,
      "text": "Syangja",
      "textNP": "स्याङग्जा"
    },
    {"id": 40, "zoneid": 7, "stateid": 4, "text": "Kaski", "textNP": "कास्की "},
    {"id": 41, "zoneid": 7, "stateid": 4, "text": "Manag", "textNP": "मनाङ "},
    {
      "id": 42,
      "zoneid": 8,
      "stateid": 4,
      "text": "Mustang",
      "textNP": "मुस्ताङ "
    },
    {"id": 43, "zoneid": 8, "stateid": 4, "text": "Parwat", "textNP": "पर्वत "},
    {
      "id": 44,
      "zoneid": 8,
      "stateid": 4,
      "text": "Myagdi",
      "textNP": "म्याग्दी "
    },
    {
      "id": 45,
      "zoneid": 8,
      "stateid": 4,
      "text": "Baglung",
      "textNP": "बागलुङ"
    },
    {"id": 46, "zoneid": 9, "stateid": 5, "text": "Gulmi", "textNP": "गुल्मी "},
    {"id": 47, "zoneid": 9, "stateid": 5, "text": "Palpa", "textNP": "पाल्पा "},
    {
      "id": 48,
      "zoneid": 9,
      "stateid": 4,
      "text": "Nawalpur",
      "textNP": "नवलपुर "
    },
    {"id": 49, "zoneid": 9, "stateid": 5, "text": "Parasi", "textNP": "परासी "},
    {
      "id": 50,
      "zoneid": 9,
      "stateid": 5,
      "text": "Rupandehi",
      "textNP": "रुपन्देही "
    },
    {
      "id": 51,
      "zoneid": 9,
      "stateid": 5,
      "text": "Arghakhanchi",
      "textNP": "अर्घाखाँची "
    },
    {
      "id": 52,
      "zoneid": 9,
      "stateid": 5,
      "text": "Kapilvastu",
      "textNP": "कपिलवस्तु "
    },
    {
      "id": 53,
      "zoneid": 10,
      "stateid": 5,
      "text": "Pyuthan",
      "textNP": "प्युठान "
    },
    {
      "id": 54,
      "zoneid": 10,
      "stateid": 5,
      "text": "Rolpa",
      "textNP": "रोल्पा "
    },
    {
      "id": 55,
      "zoneid": 10,
      "stateid": 5,
      "text": "Rukum Purba",
      "textNP": "पूर्वी रूकुम "
    },
    {
      "id": 56,
      "zoneid": 10,
      "stateid": 6,
      "text": "Rukum Paschim",
      "textNP": "पश्चिमी रूकुम "
    },
    {
      "id": 57,
      "zoneid": 10,
      "stateid": 6,
      "text": "Salyan",
      "textNP": "सल्यान "
    },
    {"id": 58, "zoneid": 10, "stateid": 5, "text": "Dang", "textNP": "दाङ "},
    {
      "id": 59,
      "zoneid": 11,
      "stateid": 5,
      "text": "Bardiya",
      "textNP": "बर्दिया "
    },
    {
      "id": 60,
      "zoneid": 11,
      "stateid": 6,
      "text": "Surkhet",
      "textNP": "सुर्खेत "
    },
    {
      "id": 61,
      "zoneid": 11,
      "stateid": 6,
      "text": "Dailekh",
      "textNP": "दैलेख "
    },
    {"id": 62, "zoneid": 11, "stateid": 5, "text": "Banke", "textNP": "बाँके "},
    {
      "id": 63,
      "zoneid": 11,
      "stateid": 6,
      "text": "Jajarkot",
      "textNP": "जाजरकोट "
    },
    {
      "id": 64,
      "zoneid": 12,
      "stateid": 6,
      "text": "Dolpa",
      "textNP": "डोल्पा "
    },
    {
      "id": 65,
      "zoneid": 12,
      "stateid": 6,
      "text": "Humla",
      "textNP": "हुम्ला "
    },
    {
      "id": 66,
      "zoneid": 12,
      "stateid": 6,
      "text": "Kalikot",
      "textNP": "कालिकोट "
    },
    {"id": 67, "zoneid": 12, "stateid": 6, "text": "Mugu", "textNP": "मुगु "},
    {"id": 68, "zoneid": 12, "stateid": 6, "text": "Jumla", "textNP": "जुम्ला"},
    {
      "id": 69,
      "zoneid": 13,
      "stateid": 7,
      "text": "Bajura",
      "textNP": "बाजुरा"
    },
    {
      "id": 70,
      "zoneid": 13,
      "stateid": 7,
      "text": "Bajhang",
      "textNP": "बझाङ "
    },
    {"id": 71, "zoneid": 13, "stateid": 7, "text": "Achham", "textNP": "अछाम "},
    {"id": 72, "zoneid": 13, "stateid": 7, "text": "Doti", "textNP": "डोटी "},
    {
      "id": 73,
      "zoneid": 1,
      "stateid": 7,
      "text": "Kailali",
      "textNP": "कैलाली "
    },
    {
      "id": 74,
      "zoneid": 14,
      "stateid": 7,
      "text": "Kanchanpur",
      "textNP": "कंचनपुर "
    },
    {
      "id": 75,
      "zoneid": 14,
      "stateid": 7,
      "text": "Dadeldhura",
      "textNP": "डडेलधुरा "
    },
    {
      "id": 76,
      "zoneid": 14,
      "stateid": 7,
      "text": "Baitadi",
      "textNP": "बैतडी "
    },
    {
      "id": 77,
      "zoneid": 14,
      "stateid": 7,
      "text": "Darchula",
      "textNP": "दार्चुला "
    }
  ],
  "vdc": [
    {"id": 1, "districtid": 1, "text": "Aathrai Tribeni Ga. Pa.", "textNP": "आठराई त्रिवेणी गाउँपालिका"},
    {"id": 2, "districtid": 1, "text": "Maiwakhola Ga. Pa.", "textNP": "मैवाखोला गाउँपालिका"},
    {"id": 3, "districtid": 1, "text": "Meringden Ga. Pa.", "textNP": "मेरिङदेन गाउँपालिका"},
    {"id": 4, "districtid": 1, "text": "Mikwakhola Ga. Pa.", "textNP": "मिक्वाखोला गाउँपालिका"},
    {"id": 5, "districtid": 1, "text": "Phaktanglung Ga. Pa.", "textNP": "फक्ताङलुङ गाउँपालिका"},
    {"id": 6, "districtid": 1, "text": "Phungling Na. Pa.", "textNP": "फुङलिङ नगरपालिका"},
    {"id": 7, "districtid": 1, "text": "Sidingba Ga. Pa.", "textNP": "सिदिङ्वा गाउँपालिका"},
    {"id": 8, "districtid": 1, "text": "Sirijangha Ga. Pa.", "textNP": "सिरीजङ्घा गाउँपालिका"},
    {"id": 9, "districtid": 1, "text": "Pathibhara Yangwarak Ga. Pa.", "textNP": "पाथीभरा याङवरक गाउँपालिका"},
    {"id": 10, "districtid": 2, "text": "Falelung Ga. Pa.", "textNP": "फालेलुङ गाउँपालिका"},
    {"id": 11, "districtid": 2, "text": "Falgunanda Ga. Pa.", "textNP": "फाल्गुनन्द गाउँपालिका"},
    {"id": 12, "districtid": 2, "text": "Hilihang Ga. Pa.", "textNP": "हिलिहाङ गाउँपालिका"},
    {"id": 13, "districtid": 2, "text": "Kummayak Ga. Pa.", "textNP": "कुम्मायक गाउँपालिका"},
    {"id": 14, "districtid": 2, "text": "Miklajung Ga. Pa.", "textNP": "मिक्लाजुङ गाउँपालिका"},
    {"id": 15, "districtid": 2, "text": "Phidim Na. Pa.", "textNP": "फिदिम नगरपालिका"},
    {"id": 16, "districtid": 2, "text": "Tumbewa Ga. Pa.", "textNP": "तुम्बेवा गाउँपालिका"},
    {"id": 17, "districtid": 2, "text": "Yangwarak Ga. Pa.", "textNP": "याङवरक गाउँपालिका"},
    {"id": 18, "districtid": 3, "text": "Chulachuli Ga. Pa.", "textNP": "चुलाचुली गाउँपालिका"},
    {"id": 19, "districtid": 3, "text": "Deumai Na. Pa.", "textNP": "देउमाई नगरपालिका"},
    {"id": 20, "districtid": 3, "text": "Fakphokthum Ga. Pa.", "textNP": "फाकफोकथुम गाउँपालिका"},
    {"id": 21, "districtid": 3, "text": "Illam Na. Pa.", "textNP": "ईलाम नगरपालिका	"},
    {"id": 22, "districtid": 3, "text": "Mai Na. Pa.", "textNP": "माई नगरपालिका"},
    {"id": 23, "districtid": 3, "text": "Maijogmai Ga. Pa.", "textNP": "माईजोगमाई गाउँपालिका"},
    {"id": 24, "districtid": 3, "text": "Mangsebung Ga. Pa.", "textNP": "माङसेबुङ गाउँपालिका"},
    {"id": 25, "districtid": 3, "text": "Rong Ga. Pa.", "textNP": "रोङ गाउँपालिका"},
    {"id": 26, "districtid": 3, "text": "Sandakpur Ga. Pa.", "textNP": "सन्दकपुर गाउँपालिका"},
    {"id": 27, "districtid": 3, "text": "Suryodaya Na. Pa.", "textNP": "सूर्योदय नगरपालिका"},
    {"id": 28, "districtid": 4, "text": "Arjundhara Na. Pa.", "textNP": "अर्जुनधारा नगरपालिका"},
    {"id": 29, "districtid": 4, "text": "Barhadashi Ga. Pa.", "textNP": "बाह्रदशी गाउँपालिका"},
    {"id": 30, "districtid": 4, "text": "Bhadrapur Na. Pa.", "textNP": "भद्रपुर नगरपालिका"},
    {"id": 31, "districtid": 4, "text": "Birtamod Na. Pa.", "textNP": "विर्तामोड नगरपालिका"},
    {"id": 32, "districtid": 4, "text": "Buddhashanti Ga. Pa.", "textNP": "बुद्धशान्ति गाउँपालिका"},
    {"id": 33, "districtid": 4, "text": "Damak Na. Pa.", "textNP": "दमक नगरपालिका"},
    {"id": 34, "districtid": 4, "text": "Gauradhaha Na. Pa.", "textNP": "गौरादह नगरपालिका"},
    {"id": 35, "districtid": 4, "text": "Gauriganj Ga. Pa.", "textNP": "गौरीगंज गाउँपालिका"},
    {"id": 36, "districtid": 4, "text": "Haldibari Ga. Pa.", "textNP": "हल्दिवारी गाउँपालिका"},
    {"id": 37, "districtid": 4, "text": "Jhapa Ga. Pa.", "textNP": "झापा गाउँपालिका"},
    {"id": 38, "districtid": 4, "text": "Kachankawal Ga. Pa.", "textNP": "कचनकवल गाउँपालिका"},
    {"id": 39, "districtid": 4, "text": "Kamal Ga. Pa.", "textNP": "कमल गाउँपालिका"},
    {"id": 40, "districtid": 4, "text": "Kankai Na. Pa.", "textNP": "कन्काई नगरपालिका"},
    {"id": 41, "districtid": 4, "text": "Mechinagar Na. Pa.", "textNP": "मेचीनगर नगरपालिका	"},
    {"id": 42, "districtid": 4, "text": "Shivasataxi Na. Pa.", "textNP": "शिवशताक्षी नगरपालिका"},
    {"id": 43, "districtid": 5, "text": "Belbari Na. Pa.", "textNP": "बेलवारी नगरपालिका"},
    {"id": 44, "districtid": 5, "text": "Biratnagar Ma. Na. Pa.", "textNP": "विराटनगर महानगरपालिका"},
    {"id": 45, "districtid": 5, "text": "Budhiganga Ga. Pa.", "textNP": "बुढीगंगा गाउँपालिका"},
    {"id": 46, "districtid": 5, "text": "Dhanpalthan Ga. Pa.", "textNP": "धनपालथान गाउँपालिका"},
    {"id": 47, "districtid": 5, "text": "Gramthan Ga. Pa.", "textNP": "ग्रामथान गाउँपालिका"},
    {"id": 48, "districtid": 5, "text": "Jahada Ga. Pa.", "textNP": "जहदा गाउँपालिका"},
    {"id": 49, "districtid": 5, "text": "Kanepokhari Ga. Pa.", "textNP": "कानेपोखरी गाउँपालिका"},
    {"id": 50, "districtid": 5, "text": "Katahari Ga. Pa.", "textNP": "कटहरी गाउँपालिका"},
    {"id": 51, "districtid": 5, "text": "Kerabari Ga. Pa.", "textNP": "केरावारी गाउँपालिका"},
    {"id": 52, "districtid": 5, "text": "Letang Na. Pa.", "textNP": "लेटाङ नगरपालिका"},
    {"id": 53, "districtid": 5, "text": "Miklajung Ga. Pa.", "textNP": "मिक्लाजुङ गाउँपालिका"},
    {"id": 54, "districtid": 5, "text": "Patahrishanishchare Na. Pa.", "textNP": "पथरी शनिश्चरे नगरपालिका"},
    {"id": 55, "districtid": 5, "text": "Rangeli Na. Pa.", "textNP": "रंगेली नगरपालिका"},
    {"id": 56, "districtid": 5, "text": "Ratuwamai Na. Pa.", "textNP": "रतुवामाई नगरपालिका"},
    {"id": 57, "districtid": 5, "text": "Sundarharaicha Na. Pa.", "textNP": "सुन्दरहरैचा नगरपालिका"},
    {"id": 58, "districtid": 5, "text": "Sunwarshi Na. Pa.", "textNP": "सुनवर्षि नगरपालिका"},
    {"id": 59, "districtid": 5, "text": "Uralabari Na. Pa.", "textNP": "उर्लावारी नगरपालिका"},
    {"id": 60, "districtid": 6, "text": "Barah Na. Pa.", "textNP": "बराहक्षेत्र नगरपालिका"},
    {"id": 61, "districtid": 6, "text": "Barju Ga. Pa.", "textNP": "बर्जु गाउँपालिका"},
    {"id": 62, "districtid": 6, "text": "Bhokraha Narsingh Ga. Pa.", "textNP": "भोक्राहा नरसिंह गाउँपालिका"},
    {"id": 63, "districtid": 6, "text": "Dewanganj Ga. Pa.", "textNP": "देवानगञ्ज गाउँपालिका	"},
    {"id": 64, "districtid": 6, "text": "Dharan Up. Ma. Na. Pa.", "textNP": "धरान उपमहानगरपालिका"},
    {"id": 65, "districtid": 6, "text": "Duhabi Na. Pa.", "textNP": "दुहवी नगरपालिका"},
    {"id": 66, "districtid": 6, "text": "Gadhi Ga. Pa.", "textNP": "गढी गाउँपालिका"},
    {"id": 67, "districtid": 6, "text": "Harinagar Ga. Pa.", "textNP": "हरिनगर गाउँपालिका"},
    {"id": 68, "districtid": 6, "text": "Inaruwa Na. Pa.", "textNP": "ईनरुवा नगरपालिका"},
    {"id": 69, "districtid": 6, "text": "Itahari Up. Ma. Na. Pa.", "textNP": "ईटहरी उपमहानगरपालिका"},
    {"id": 70, "districtid": 6, "text": "Koshi Ga. Pa.", "textNP": "कोशी गाउँपालिका"},
    {"id": 71, "districtid": 6, "text": "Ramdhuni Na. Pa.", "textNP": "रामधुनी नगरपालिका"},
    {"id": 72, "districtid": 7, "text": "Chaubise Ga. Pa.", "textNP": "चौविसे गाउँपालिका"},
    {"id": 73, "districtid": 7, "text": "Chhathar Jorpati Ga. Pa.", "textNP": "छथर जोरपाटी गाउँपालिका"},
    {"id": 74, "districtid": 7, "text": "Dhankuta Na. Pa.", "textNP": "धनकुटा नगरपालिका"},
    {"id": 75, "districtid": 7, "text": "Shahidbhumi Ga. Pa.", "textNP": "सहिदभूमि गाउँपालिका"},
    {"id": 76, "districtid": 7, "text": "Sangurigadhi Ga. Pa.", "textNP": "साँगुरीगढी गाउँपालिका"},
    {"id": 77, "districtid": 7, "text": "Mahalaxmi Na. Pa.", "textNP": "महालक्ष्मी नगरपालिका"},
    {"id": 78, "districtid": 7, "text": "Pakhribas Na. Pa.", "textNP": "पाख्रिबास नगरपालिका"},
    {"id": 79, "districtid": 8, "text": "Bhotkhola Ga. Pa.", "textNP": "भोटखोला गाउँपालिका"},
    {"id": 80, "districtid": 8, "text": "Chainpur Na. Pa.", "textNP": "चैनपुर नगरपालिका"},
    {"id": 81, "districtid": 8, "text": "Chichila Ga. Pa.", "textNP": "चिचिला गाउँपालिका"},
    {"id": 82, "districtid": 8, "text": "Dharmadevi Na. Pa.", "textNP": "धर्मदेवी नगरपालिका"},
    {"id": 83, "districtid": 8, "text": "Khandbari Na. Pa.", "textNP": "खाँदवारी नगरपालिका"},
    {"id": 84, "districtid": 8, "text": "Madi Na. Pa.", "textNP": "मादी नगरपालिका"},
    {"id": 85, "districtid": 8, "text": "Makalu Ga. Pa.", "textNP": "मकालु गाउँपालिका"},
    {"id": 86, "districtid": 8, "text": "Panchakhapan Na. Pa.", "textNP": "पाँचखपन नगरपालिका"},
    {"id": 87, "districtid": 8, "text": "Sabhapokhari Ga. Pa.", "textNP": "सभापोखरी गाउँपालिका"},
    {"id": 88, "districtid": 8, "text": "Silichong Ga. Pa.", "textNP": "सिलीचोङ गाउँपालिका"},
    {"id": 89, "districtid": 9, "text": "Aamchowk Ga. Pa.", "textNP": "आमचोक गाउँपालिका"},
    {"id": 90, "districtid": 9, "text": "Arun Ga. Pa.", "textNP": "अरुण गाउँपालिका"},
    {"id": 91, "districtid": 9, "text": "Bhojpur Na. Pa.", "textNP": "भोजपुर नगरपालिका"},
    {"id": 92, "districtid": 9, "text": "Hatuwagadhi Ga. Pa.", "textNP": "हतुवागढी गाउँपालिका"},
    {"id": 93, "districtid": 9, "text": "Pauwadungma Ga. Pa.", "textNP": "पौवादुङमा गाउँपालिका"},
    {"id": 94, "districtid": 9, "text": "Ramprasad Rai Ga. Pa.", "textNP": "रामप्रसाद राई गाउँपालिका"},
    {"id": 95, "districtid": 9, "text": "Salpasilichho Ga. Pa.", "textNP": "साल्पासिलिछो गाउँपालिका"},
    {"id": 96, "districtid": 9, "text": "Shadananda Na. Pa.", "textNP": "षडानन्द नगरपालिका"},
    {"id": 97, "districtid": 9, "text": "Tyamkemaiyung Ga. Pa.", "textNP": "टेम्केमैयुङ गाउँपालिका"},
    {"id": 98, "districtid": 10, "text": "Aathrai Ga. Pa.", "textNP": "आठराई गाउँपालिका"},
    {"id": 99, "districtid": 10, "text": "Chhathar Ga. Pa.", "textNP": "छथर गाउँपालिका"},
    {"id": 100, "districtid": 10, "text": "Laligurans Na. Pa.", "textNP": "लालीगुराँस नगरपालिका"},
    {"id": 101, "districtid": 10, "text": "Menchayam Ga. Pa.", "textNP": "मेन्छयायेम गाउँपालिका"},
    {"id": 102, "districtid": 10, "text": "Myanglung Na. Pa.", "textNP": "म्याङलुङ नगरपालिका"},
    {"id": 103, "districtid": 10, "text": "Phedap Ga. Pa.", "textNP": "फेदाप गाउँपालिका"},
    {"id": 104, "districtid": 11, "text": "Champadevi Ga. Pa.", "textNP": "चम्पादेवी गाउँपालिका"},
    {"id": 105, "districtid": 11, "text": "Chisankhugadhi Ga. Pa.", "textNP": "चिशंखुगढी गाउँपालिका"},
    {"id": 106, "districtid": 11, "text": "Khijidemba Ga. Pa.", "textNP": "खिजिदेम्बा गाउँपालिका"},
    {"id": 107, "districtid": 11, "text": "Likhu Ga. Pa.", "textNP": "लिखु गाउँपालिका"},
    {"id": 108, "districtid": 11, "text": "Manebhanjyang Ga. Pa.", "textNP": "मानेभञ्याङ गाउँपालिका"},
    {"id": 109, "districtid": 11, "text": "Molung Ga. Pa.", "textNP": "मोलुङ गाउँपालिका"},
    {"id": 110, "districtid": 11, "text": "Siddhicharan Na. Pa.", "textNP": "सिद्दिचरण नगरपालिका"},
    {"id": 111, "districtid": 11, "text": "Sunkoshi Ga. Pa.", "textNP": "सुनकोशी गाउँपालिका"},
    {"id": 112, "districtid": 12, "text": "Ainselukhark Ga. Pa.", "textNP": "ऐसेलुखर्क गाउँपालिका"},
    {"id": 113, "districtid": 12, "text": "Barahapokhari Ga. Pa.", "textNP": "वराहपोखरी गाउँपालिका"},
    {"id": 114, "districtid": 12, "text": "Diprung Ga. Pa.", "textNP": "दिप्रुङ चुइचुम्मा गाउँपालिका"},
    {"id": 115, "districtid": 12, "text": "Halesi Tuwachung Na. Pa.", "textNP": "हलेसी तुवाचुङ नगरपालिका"},
    {"id": 116, "districtid": 12, "text": "Jantedhunga Ga. Pa.", "textNP": "जन्तेढुंगा गाउँपालिका	"},
    {"id": 117, "districtid": 12, "text": "Kepilasagadhi Ga. Pa.", "textNP": "केपिलासगढी गाउँपालिका"},
    {"id": 118, "districtid": 12, "text": "Khotehang Ga. Pa.", "textNP": "खोटेहाङ गाउँपालिका"},
    {"id": 119, "districtid": 12, "text": "Rawa Besi Ga. Pa.", "textNP": "रावा बेसी गाउँपालिका"},
    {"id": 120, "districtid": 12, "text": "Rupakot Majhuwagadhi Na. Pa.", "textNP": "दिक्तेल रुपाकोट मझुवागढी नगरपालिका"},
    {"id": 121, "districtid": 12, "text": "Sakela Ga. Pa.", "textNP": "साकेला गाउँपालिका"},
    {"id": 122, "districtid": 13, "text": "Thulung Dudhkoshi Ga. Pa.", "textNP": "थुलुङ दुधकोशी गाउँपालिका"},
    {"id": 123, "districtid": 13, "text": "Dudhkoshi Ga. Pa.", "textNP": "माप्य दुधकोशी गाउँपालिका"},
    {"id": 124, "districtid": 13, "text": "Khumbupasanglahmu Ga. Pa.", "textNP": "खुम्वु पासाङल्हमु गाउँपालिका"},
    {"id": 125, "districtid": 13, "text": "Likhupike Ga. Pa.", "textNP": "लिखु पिके गाउँपालिका"},
    {"id": 126, "districtid": 13, "text": "Mahakulung Ga. Pa.", "textNP": "माहाकुलुङ गाउँपालिका"},
    {"id": 127, "districtid": 13, "text": "Nechasalyan Ga. Pa.", "textNP": "नेचासल्यान गाउँपालिका"},
    {"id": 128, "districtid": 13, "text": "Solududhakunda Na. Pa.", "textNP": "सोलुदुधकुण्ड नगरपालिका"},
    {"id": 129, "districtid": 13, "text": "Sotang Ga. Pa.", "textNP": "सोताङ गाउँपालिका"},
    {"id": 130, "districtid": 14, "text": "Belaka Na. Pa.", "textNP": "वेलका नगरपालिका"},
    {"id": 131, "districtid": 14, "text": "Chaudandigadhi Na. Pa.", "textNP": "चौदण्डीगढी नगरपालिका"},
    {"id": 132, "districtid": 14, "text": "Katari Na. Pa.", "textNP": "कटारी नगरपालिका"},
    {"id": 133, "districtid": 14, "text": "Rautamai Ga. Pa.", "textNP": "रौतामाई गाउँपालिका"},
    {"id": 134, "districtid": 14, "text": "Limchungbung Ga. Pa.", "textNP": "लिम्चुङ्बुङ गाउँपालिका"},
    {"id": 135, "districtid": 14, "text": "Tapli Ga. Pa.", "textNP": "ताप्ली गाउँपालिका"},
    {"id": 136, "districtid": 14, "text": "Triyuga Na. Pa.", "textNP": "त्रियुगा नगरपालिका"},
    {"id": 137, "districtid": 14, "text": "Udayapurgadhi Ga. Pa.", "textNP": "उदयपुरगढी गाउँपालिका"},
    {"id": 138, "districtid": 15, "text": "Agnisair Krishna Savaran Ga. Pa.", "textNP": "अग्निसाइर कृष्णासरवन गाउँपालिका"},
    {"id": 139, "districtid": 15, "text": "Balan Bihul Ga. Pa.", "textNP": "बलान-बिहुल गाउँपालिका"},
    {"id": 140, "districtid": 15, "text": "Rajgadh Ga. Pa.", "textNP": "राजगढ गाउँपालिका"},
    {"id": 141, "districtid": 15, "text": "Bishnupur Ga. Pa.", "textNP": "बिष्णुपुर गाउँपालिका	"},
    {"id": 142, "districtid": 15, "text": "Bode Barsain Na. Pa.", "textNP": "बोदेबरसाईन नगरपालिका"},
    {"id": 143, "districtid": 15, "text": "Chhinnamasta Ga. Pa.", "textNP": "छिन्नमस्ता गाउँपालिका"},
    {"id": 144, "districtid": 15, "text": "Dakneshwori Na. Pa.", "textNP": "डाक्नेश्वरी नगरपालिका"},
    {"id": 145, "districtid": 15, "text": "Hanumannagar Kankalini Na. Pa.", "textNP": "हनुमाननगर कङ्‌कालिनी नगरपालिका"},
    {"id": 146, "districtid": 15, "text": "Kanchanrup Na. Pa.", "textNP": "कञ्चनरुप नगरपालिका"},
    {"id": 147, "districtid": 15, "text": "Khadak Na. Pa.", "textNP": "खडक नगरपालिका"},
    {"id": 148, "districtid": 15, "text": "Mahadeva Ga. Pa.", "textNP": "महादेवा गाउँपालिका"},
    {"id": 149, "districtid": 15, "text": "Rajbiraj Na. Pa.", "textNP": "राजविराज नगरपालिका"},
    {"id": 150, "districtid": 15, "text": "Rupani Ga. Pa.", "textNP": "रुपनी गाउँपालिका"},
    {"id": 151, "districtid": 15, "text": "Saptakoshi Na. Pa.", "textNP": "सप्तकोशी नगरपालिका"},
    {"id": 152, "districtid": 15, "text": "Shambhunath Na. Pa.", "textNP": "शम्भुनाथ नगरपालिका	"},
    {"id": 153, "districtid": 15, "text": "Surunga Na. Pa.", "textNP": "सुरुङ्‍गा नगरपालिका"},
    {"id": 154, "districtid": 15, "text": "Tilathi Koiladi Ga. Pa.", "textNP": "तिलाठी कोईलाडी गाउँपालिका"},
    {"id": 155, "districtid": 15, "text": "Tirahut Ga. Pa.", "textNP": "तिरहुत गाउँपालिका"},
    {"id": 156, "districtid": 16, "text": "Arnama Ga. Pa.", "textNP": "अर्नमा गाउँपालिका"},
    {"id": 157, "districtid": 16, "text": "Aurahi Ga. Pa.", "textNP": "औरही गाउँपालिका"},
    {"id": 158, "districtid": 16, "text": "Bariyarpatti Ga. Pa.", "textNP": "बरियारपट्टी गाउँपालिका"},
    {"id": 159, "districtid": 16, "text": "Bhagawanpur Ga. Pa.", "textNP": "भगवानपुर गाउँपालिका"},
    {"id": 160, "districtid": 16, "text": "Bishnupur Ga. Pa.", "textNP": "विष्णुपुर गाउँपालिका"},
    {"id": 161, "districtid": 16, "text": "Dhangadhimai Na. Pa.", "textNP": "धनगढीमाई नगरपालिका"},
    {"id": 162, "districtid": 16, "text": "Golbazar Na. Pa.", "textNP": "गोलबजार नगरपालिका"},
    {"id": 163, "districtid": 16, "text": "Kalyanpur Na. Pa.", "textNP": "कल्याणपुर नगरपालिका"},
    {"id": 164, "districtid": 16, "text": "Karjanha Na. Pa.", "textNP": "कर्जन्हा नगरपालिका"},
    {"id": 165, "districtid": 16, "text": "Lahan Na. Pa.", "textNP": "लहान नगरपालिका"},
    {"id": 166, "districtid": 16, "text": "Laxmipur Patari Ga. Pa.", "textNP": "लक्ष्मीपुर पतारी गाउँपालिका"},
    {"id": 167, "districtid": 16, "text": "Mirchaiya Na. Pa.", "textNP": "मिर्चैयाँ नगरपालिका"},
    {"id": 168, "districtid": 16, "text": "Naraha Ga. Pa.", "textNP": "नरहा गाउँपालिका"},
    {"id": 169, "districtid": 16, "text": "Nawarajpur Ga. Pa.", "textNP": "नवराजपुर गाउँपालिका"},
    {"id": 170, "districtid": 16, "text": "Sakhuwanankarkatti Ga. Pa.", "textNP": "सखुवानान्कारकट्टी गाउँपालिका"},
    {"id": 171, "districtid": 16, "text": "Siraha Na. Pa.", "textNP": "सिरहा नगरपालिका"},
    {"id": 172, "districtid": 16, "text": "Sukhipur Na. Pa.", "textNP": "सुखीपुर नगरपालिका"},
    {"id": 173, "districtid": 17, "text": "Aaurahi Ga. Pa.", "textNP": "औरही गाउँपालिका"},
    {"id": 174, "districtid": 17, "text": "Bateshwor Ga. Pa.", "textNP": "बटेश्वर गाउँपालिका	"},
    {"id": 175, "districtid": 17, "text": "Bideha Na. Pa.", "textNP": "विदेह नगरपालिका"},
    {"id": 176, "districtid": 17, "text": "Chhireshwornath Na. Pa.", "textNP": "क्षिरेश्वरनाथ नगरपालिका"},
    {"id": 177, "districtid": 17, "text": "Dhanauji Ga. Pa.", "textNP": "धनौजी गाउँपालिका"},
    {"id": 178, "districtid": 17, "text": "Dhanusadham Na. Pa.", "textNP": "धनुषाधाम नगरपालिका"},
    {"id": 179, "districtid": 17, "text": "Ganeshman Charnath Na. Pa.", "textNP": "गणेशमान चारनाथ नगरपालिका"},
    {"id": 180, "districtid": 17, "text": "Hansapur Na. Pa.", "textNP": "हंसपुर नगरपालिका"},
    {"id": 181, "districtid": 17, "text": "Janaknandani Ga. Pa.", "textNP": "जनकनन्दिनी गाउँपालिका"},
    {"id": 182, "districtid": 17, "text": "Janakpur Up. Ma. Na. Pa.", "textNP": "जनकपुरधाम उपमहानगरपालिका"},
    {"id": 183, "districtid": 17, "text": "Kamala Na. Pa.", "textNP": "कमला नगरपालिका"},
    {"id": 184, "districtid": 17, "text": "Lakshminiya Ga. Pa.", "textNP": "लक्ष्मीनिया गाउँपालिका"},
    {"id": 185, "districtid": 17, "text": "Mithila Na. Pa.", "textNP": "मिथिला नगरपालिका"},
    {"id": 186, "districtid": 17, "text": "Mithila Bihari Na. Pa.", "textNP": "मिथिला बिहारी नगरपालिका"},
    {"id": 187, "districtid": 17, "text": "Mukhiyapatti Musarmiya Ga. Pa.", "textNP": "मुखियापट्टी मुसहरमिया गाउँपालिका"},
    {"id": 188, "districtid": 17, "text": "Nagarain Na. Pa.", "textNP": "नगराइन नगरपालिका	"},
    {"id": 189, "districtid": 17, "text": "Sabaila Na. Pa.", "textNP": "सबैला नगरपालिका	"},
    {"id": 190, "districtid": 17, "text": "Sahidnagar Na. Pa.", "textNP": "शहीदनगर नगरपालिका"},
    {"id": 191, "districtid": 18, "text": "Aurahi Na. Pa.", "textNP": "औरही नगरपालिका"},
    {"id": 192, "districtid": 18, "text": "Balwa Na. Pa.", "textNP": "बलवा नगरपालिका"},
    {"id": 193, "districtid": 18, "text": "Bardibas Na. Pa.", "textNP": "बर्दिबास नगरपालिका"},
    {"id": 194, "districtid": 18, "text": "Bhangaha Na. Pa.", "textNP": "भँगाहा नगरपालिका"},
    {"id": 195, "districtid": 18, "text": "Ekdanra Ga. Pa.", "textNP": "एकडारा गाउँपालिका"},
    {"id": 196, "districtid": 18, "text": "Gaushala Na. Pa.", "textNP": "गौशाला नगरपालिका"},
    {"id": 197, "districtid": 18, "text": "Jaleswor Na. Pa.", "textNP": "जलेश्वर नगरपालिका"},
    {"id": 198, "districtid": 18, "text": "Loharpatti Na. Pa.", "textNP": "लोहरपट्टी नगरपालिका"},
    {"id": 199, "districtid": 18, "text": "Mahottari Ga. Pa.", "textNP": "महोत्तरी गाउँपालिका"},
    {"id": 200, "districtid": 18, "text": "Manra Siswa Na. Pa.", "textNP": "मनरा शिसवा नगरपालिका"},
    {"id": 201, "districtid": 18, "text": "Matihani Na. Pa.", "textNP": "मटिहानी नगरपालिका"},
    {"id": 202, "districtid": 18, "text": "Pipra Ga. Pa.", "textNP": "पिपरा गाउँपालिका"},
    {"id": 203, "districtid": 18, "text": "Ramgopalpur Na. Pa.", "textNP": "रामगोपालपुर नगरपालिका"},
    {"id": 204, "districtid": 18, "text": "Samsi Ga. Pa.", "textNP": "साम्सी गाउँपालिका"},
    {"id": 205, "districtid": 18, "text": "Sonama Ga. Pa.", "textNP": "सोनमा गाउँपालिका"},
    {"id": 206, "districtid": 19, "text": "Bagmati Na. Pa.", "textNP": "बागमती नगरपालिका"},
    {"id": 207, "districtid": 19, "text": "Balara Na. Pa.", "textNP": "बलरा नगरपालिका"},
    {"id": 208, "districtid": 19, "text": "Barahathawa Na. Pa.", "textNP": "बरहथवा नगरपालिका"},
    {"id": 209, "districtid": 19, "text": "Basbariya Ga. Pa.", "textNP": "बसबरीया गाउँपालिका"},
    {"id": 210, "districtid": 19, "text": "Bishnu Ga. Pa.", "textNP": "विष्णु गाउँपालिका"},
    {"id": 211, "districtid": 19, "text": "Bramhapuri Ga. Pa.", "textNP": "ब्रह्मपुरी गाउँपालिका"},
    {"id": 212, "districtid": 19, "text": "Chakraghatta Ga. Pa.", "textNP": "चक्रघट्टा गाउँपालिका	"},
    {"id": 213, "districtid": 19, "text": "Chandranagar Ga. Pa.", "textNP": "चन्द्रनगर गाउँपालिका	"},
    {"id": 214, "districtid": 19, "text": "Dhankaul Ga. Pa.", "textNP": "धनकौल गाउँपालिका"},
    {"id": 215, "districtid": 19, "text": "Godaita Na. Pa.", "textNP": "गोडैटा नगरपालिका"},
    {"id": 216, "districtid": 19, "text": "Haripur Na. Pa.", "textNP": "हरिपुर नगरपालिका	"},
    {"id": 217, "districtid": 19, "text": "Haripurwa Na. Pa.", "textNP": "हरिपुर्वा नगरपालिका"},
    {"id": 218, "districtid": 19, "text": "Hariwan Na. Pa.", "textNP": "हरिवन नगरपालिका	"},
    {"id": 219, "districtid": 19, "text": "Ishworpur Na. Pa.", "textNP": "ईश्वरपुर नगरपालिका"},
    {"id": 220, "districtid": 19, "text": "Kabilasi Na. Pa.", "textNP": "कविलासी नगरपालिका"},
    {"id": 221, "districtid": 19, "text": "Kaudena Ga. Pa.", "textNP": "कौडेना गाउँपालिका"},
    {"id": 222, "districtid": 19, "text": "Lalbandi Na. Pa.", "textNP": "लालबन्दी नगरपालिका"},
    {"id": 223, "districtid": 19, "text": "Malangawa Na. Pa.", "textNP": "मलंगवा नगरपालिका"},
    {"id": 224, "districtid": 19, "text": "Parsa Ga. Pa.", "textNP": "पर्सा गाउँपालिका"},
    {"id": 225, "districtid": 19, "text": "Ramnagar Ga. Pa.", "textNP": "रामनगर गाउँपालिका"},
    {"id": 226, "districtid": 20, "text": "Dudhouli Na. Pa.", "textNP": "	दुधौली नगरपालिका"},
    {"id": 227, "districtid": 20, "text": "Ghanglekh Ga. Pa.", "textNP": "घ्याङलेख गाउँपालिका"},
    {"id": 228, "districtid": 20, "text": "Golanjor Ga. Pa.", "textNP": "गोलन्जर गाउँपालिका"},
    {"id": 229, "districtid": 20, "text": "Hariharpurgadhi Ga. Pa.", "textNP": "हरिहरपुरगढी गाउँपालिका"},
    {"id": 230, "districtid": 20, "text": "Kamalamai Na. Pa.", "textNP": "कमलामाई नगरपालिका"},
    {"id": 231, "districtid": 20, "text": "Marin Ga. Pa.", "textNP": "मरिण गाउँपालिका"},
    {"id": 232, "districtid": 20, "text": "Phikkal Ga. Pa.", "textNP": "फिक्कल गाउँपालिका"},
    {"id": 233, "districtid": 20, "text": "Sunkoshi Ga. Pa.", "textNP": "सुनकोशी गाउँपालिका	"},
    {"id": 234, "districtid": 20, "text": "Tinpatan Ga. Pa.", "textNP": "तीनपाटन गाउँपालिका"},
    {"id": 235, "districtid": 21, "text": "Doramba Ga. Pa.", "textNP": "दोरम्बा शैंलुङ गाउँपालिका"},
    {"id": 236, "districtid": 21, "text": "Gokulganga Ga. Pa.", "textNP": "गोकुलगङ्गा गाउँपालिका"},
    {"id": 237, "districtid": 21, "text": "Khadadevi Ga. Pa.", "textNP": "खाँडादेवी गाउँपालिका"},
    {"id": 238, "districtid": 21, "text": "Likhu Tamakoshi Ga. Pa.", "textNP": "लिखु तामाकोशी गाउँपालिका"},
    {"id": 239, "districtid": 21, "text": "Manthali Na. Pa.", "textNP": "मन्थली नगरपालिका"},
    {"id": 240, "districtid": 21, "text": "Ramechhap Na. Pa.", "textNP": "रामेछाप नगरपालिका"},
    {"id": 241, "districtid": 21, "text": "Sunapati Ga. Pa.", "textNP": "सुनापती गाउँपालिका	"},
    {"id": 242, "districtid": 21, "text": "Umakunda Ga. Pa.", "textNP": "उमाकुण्ड गाउँपालिका"},
    {"id": 243, "districtid": 22, "text": "Baiteshwor Ga. Pa.", "textNP": "तेश्वर गाउँपालिका"},
    {"id": 244, "districtid": 22, "text": "Bhimeshwor Na. Pa.", "textNP": "भिमेश्वर नगरपालिका"},
    {"id": 245, "districtid": 22, "text": "Bigu Ga. Pa.", "textNP": "विगु गाउँपालिका"},
    {"id": 246, "districtid": 22, "text": "Gaurishankar Ga. Pa.", "textNP": "गौरीशङ्कर गाउँपालिका"},
    {"id": 247, "districtid": 22, "text": "Jiri Na. Pa.", "textNP": "जिरी नगरपालिका"},
    {"id": 248, "districtid": 22, "text": "Kalinchok Ga. Pa.", "textNP": "कालिन्चोक गाउँपालिका"},
    {"id": 249, "districtid": 22, "text": "Melung Ga. Pa.", "textNP": "मेलुङ्ग गाउँपालिका"},
    {"id": 250, "districtid": 22, "text": "Sailung Ga. Pa.", "textNP": "शैलुङ्ग गाउँपालिका"},
    {"id": 251, "districtid": 22, "text": "Tamakoshi Ga. Pa.", "textNP": "तामाकोशी गाउँपालिका"},
    {"id": 252, "districtid": 23, "text": "Balefi Ga. Pa.", "textNP": "बलेफी गाउँपालिका"},
    {"id": 253, "districtid": 23, "text": "Barhabise Na. Pa.", "textNP": "बाह्रविसे नगरपालिका"},
    {"id": 254, "districtid": 23, "text": "Bhotekoshi Ga. Pa.", "textNP": "भोटेकोशी गाउँपालिका"},
    {"id": 255, "districtid": 23, "text": "Chautara SangachokGadhi Na. Pa.", "textNP": "चौतारा साँगाचोकगढी नगरपालिका"},
    {"id": 256, "districtid": 23, "text": "Helambu Ga. Pa.", "textNP": "हेलम्बु गाउँपालिका"},
    {"id": 257, "districtid": 23, "text": "Indrawati Ga. Pa.", "textNP": "ईन्द्रावती गाउँपालिका"},
    {"id": 258, "districtid": 23, "text": "Jugal Ga. Pa.", "textNP": "जुगल गाउँपालिका"},
    {"id": 259, "districtid": 23, "text": "Lisangkhu Pakhar Ga. Pa.", "textNP": "लिसङ्खु पाखर गाउँपालिका"},
    {"id": 260, "districtid": 23, "text": "Melamchi Na. Pa.", "textNP": "मेलम्ची नगरपालिका"},
    {"id": 261, "districtid": 23, "text": "Panchpokhari Thangpal Ga. Pa.", "textNP": "पाँचपोखरी थाङपाल गाउँपालिका"},
    {"id": 262, "districtid": 23, "text": "Sunkoshi Ga. Pa.", "textNP": "सुनकोशी गाउँपालिका"},
    {"id": 263, "districtid": 23, "text": "Tripurasundari Ga. Pa.", "textNP": "त्रिपुरासुन्दरी गाउँपालिका"},
    {"id": 264, "districtid": 24, "text": "Banepa Na. Pa.", "textNP": "बनेपा नगरपालिका"},
    {"id": 265, "districtid": 24, "text": "Bethanchowk Ga. Pa.", "textNP": "बेथानचोक गाउँपालिका"},
    {"id": 266, "districtid": 24, "text": "Bhumlu Ga. Pa.", "textNP": "भुम्लु गाउँपालिका"},
    {"id": 267, "districtid": 24, "text": "Chaurideurali Ga. Pa.", "textNP": "चौंरीदेउराली गाउँपालिका"},
    {"id": 268, "districtid": 24, "text": "Dhulikhel Na. Pa.", "textNP": "धुलिखेल नगरपालिका"},
    {"id": 269, "districtid": 24, "text": "Khanikhola Ga. Pa.", "textNP": "खानीखोला गाउँपालिका"},
    {"id": 270, "districtid": 24, "text": "Mahabharat Ga. Pa.", "textNP": "महाभारत गाँउपालिका"},
    {"id": 271, "districtid": 24, "text": "Mandandeupur Na. Pa.", "textNP": "मण्डनदेउपुर नगरपालिका"},
    {"id": 272, "districtid": 24, "text": "Namobuddha Na. Pa.", "textNP": "नमोबुद्ध नगरपालिका"},
    {"id": 273, "districtid": 24, "text": "Panauti Na. Pa.", "textNP": "पनौती नगरपालिका"},
    {"id": 274, "districtid": 24, "text": "Panchkhal Na. Pa.", "textNP": "पाँचखाल नगरपालिका	"},
    {"id": 275, "districtid": 24, "text": "Roshi Ga. Pa.", "textNP": "रोशी गाउँपालिका"},
    {"id": 276, "districtid": 24, "text": "Temal Ga. Pa.", "textNP": "तेमाल गाउँपालिका"},
    {"id": 277, "districtid": 25, "text": "Bagmati Ga. Pa.", "textNP": "बागमती गाउँपालिका"},
    {"id": 278, "districtid": 25, "text": "Godawari Na. Pa.", "textNP": "गोदावरी नगरपालिका"},
    {"id": 279, "districtid": 25, "text": "Konjyosom Ga. Pa.", "textNP": "	कोन्ज्योसोम गाउँपालिका"},
    {"id": 280, "districtid": 25, "text": "Lalitpur Ma. Na. Pa.", "textNP": "ललितपुर महानगरपालिका"},
    {"id": 281, "districtid": 25, "text": "Mahalaxmi Na. Pa.", "textNP": "महालक्ष्मी नगरपालिका"},
    {"id": 282, "districtid": 25, "text": "Mahankal Ga. Pa.", "textNP": "महाङ्काल गाउँपालिका"},
    {"id": 283, "districtid": 26, "text": "Bhaktapur Na. Pa.", "textNP": "भक्तपुर नगरपालिका"},
    {"id": 284, "districtid": 26, "text": "Changunarayan Na. Pa.", "textNP": "चाँगुनारायण नगरपालिका"},
    {"id": 285, "districtid": 26, "text": "Madhyapur Thimi Na. Pa.", "textNP": "मध्यपुर थिमी नगरपालिका"},
    {"id": 286, "districtid": 26, "text": "Suryabinayak Na. Pa.", "textNP": "सूर्यविनायक नगरपालिका"},
    {"id": 287, "districtid": 27, "text": "Budhanilakantha Na. Pa.", "textNP": "बुढानिलकण्ठ नगरपालिका"},
    {"id": 288, "districtid": 27, "text": "Chandragiri Na. Pa.", "textNP": "चन्द्रागिरी नगरपालिका"},
    {"id": 289, "districtid": 27, "text": "Dakshinkali Na. Pa.", "textNP": "दक्षिणकाली नगरपालिका"},
    {"id": 290, "districtid": 27, "text": "Gokarneshwor Na. Pa.", "textNP": "गोकर्णेश्वर नगरपालिका"},
    {"id": 291, "districtid": 27, "text": "Kageshwori Manahora Na. Pa.", "textNP": "कागेश्वरी मनोहरा नगरपालिका"},
    {"id": 292, "districtid": 27, "text": "Kathmandu Ma. Na. Pa.", "textNP": "काठमाण्डौं महानगरपालिका"},
    {"id": 293, "districtid": 27, "text": "Kirtipur Na. Pa.", "textNP": "कीर्तिपुर नगरपालिका"},
    {"id": 294, "districtid": 27, "text": "Nagarjun Na. Pa.", "textNP": "नागार्जुन नगरपालिका"},
    {"id": 295, "districtid": 27, "text": "Shankharapur Na. Pa.", "textNP": "शङ्खरापुर नगरपालिका"},
    {"id": 296, "districtid": 27, "text": "Tarakeshwor Na. Pa.", "textNP": "तारकेश्वर नगरपालिका"},
    {"id": 297, "districtid": 27, "text": "Tokha Na. Pa.", "textNP": "टोखा नगरपालिका"},
    {"id": 298, "districtid": 28, "text": "Belkotgadhi Na. Pa.", "textNP": "v"},
    {"id": 299, "districtid": 28, "text": "Bidur Na. Pa.", "textNP": "विदुर नगरपालिका"},
    {"id": 300, "districtid": 28, "text": "Dupcheshwar Ga. Pa.", "textNP": "दुप्चेश्वर गाउँपालिका"},
    {"id": 301, "districtid": 28, "text": "Kakani Ga. Pa.", "textNP": "ककनी गाउँपालिका"},
    {"id": 302, "districtid": 28, "text": "Kispang Ga. Pa.", "textNP": "किस्पाङ गाउँपालिका"},
    {"id": 303, "districtid": 28, "text": "Likhu Ga. Pa.", "textNP": "लिखु गाउँपालिका"},
    {"id": 304, "districtid": 28, "text": "Meghang Ga. Pa.", "textNP": "म्यगङ गाउँपालिका"},
    {"id": 305, "districtid": 28, "text": "Panchakanya Ga. Pa.", "textNP": "पञ्चकन्या गाउँपालिका"},
    {"id": 306, "districtid": 28, "text": "Shivapuri Ga. Pa.", "textNP": "शिवपुरी गाउँपालिका"},
    {"id": 307, "districtid": 28, "text": "Suryagadhi Ga. Pa.", "textNP": "सुर्यगढी गाउँपालिका"},
    {"id": 308, "districtid": 28, "text": "Tadi Ga. Pa.", "textNP": "तादी गाउँपालिका"},
    {"id": 309, "districtid": 28, "text": "Tarkeshwar Ga. Pa.", "textNP": "तारकेश्वर गाउँपालिका"},
    {"id": 310, "districtid": 29, "text": "Gosaikunda Ga. Pa.", "textNP": "गोसाईकुण्ड गाउँपालिका"},
    {"id": 311, "districtid": 29, "text": "Kalika Ga. Pa.", "textNP": "कालिका गाउँपालिका"},
    {"id": 312, "districtid": 29, "text": "Naukunda Ga. Pa.", "textNP": "नौकुण्ड गाउँपालिका"},
    {"id": 313, "districtid": 29, "text": "Parbati Kunda Ga. Pa.", "textNP": "आमाछोदिङमो गाउँपालिका"},
    {"id": 314, "districtid": 29, "text": "Uttargaya Ga. Pa.", "textNP": "उत्तरगया गाउँपालिका"},
    {"id": 315, "districtid": 30, "text": "Benighat Rorang Ga. Pa.", "textNP": "बेनीघाट रोराङ्ग गाउँपालिका"},
    {"id": 316, "districtid": 30, "text": "Dhunibesi Na. Pa.", "textNP": "धुनीबेंशी नगरपालिका"},
    {"id": 317, "districtid": 30, "text": "Gajuri Ga. Pa.", "textNP": "गजुरी गाउँपालिका"},
    {"id": 318, "districtid": 30, "text": "Galchi Ga. Pa.", "textNP": "गल्छी गाउँपालिका"},
    {"id": 319, "districtid": 30, "text": "Gangajamuna Ga. Pa.", "textNP": "गङ्गाजमुना गाउँपालिका"},
    {"id": 320, "districtid": 30, "text": "Jwalamukhi Ga. Pa.", "textNP": "ज्वालामूखी गाउँपालिका"},
    {"id": 321, "districtid": 30, "text": "Khaniyabash Ga. Pa.", "textNP": "खनियाबास गाउँपालिका"},
    {"id": 322, "districtid": 30, "text": "Netrawati Dabjong Ga. Pa.", "textNP": "नेत्रावती डबजोङ गाउँपालिका"},
    {"id": 323, "districtid": 30, "text": "Nilakantha Na. Pa.", "textNP": "निलकण्ठ नगरपालिका"},
    {"id": 324, "districtid": 30, "text": "Rubi Valley Ga. Pa.", "textNP": "रुवी भ्याली गाउँपालिका"},
    {"id": 325, "districtid": 30, "text": "Siddhalek Ga. Pa.", "textNP": "सिद्धलेक गाउँपालिका"},
    {"id": 326, "districtid": 30, "text": "Thakre Ga. Pa.", "textNP": "थाक्रे गाउँपालिका"},
    {"id": 327, "districtid": 30, "text": "Tripura Sundari Ga. Pa.", "textNP": "त्रिपुरासुन्दरी गाउँपालिका"},
    {"id": 328, "districtid": 31, "text": "Bagmati Ga. Pa.", "textNP": "बाग्मति गाउँपालिका"},
    {"id": 329, "districtid": 31, "text": "Bakaiya Ga. Pa.", "textNP": "बकैया गाउँपालिका"},
    {"id": 330, "districtid": 31, "text": "Bhimphedi Ga. Pa.", "textNP": "भिमफेदी गाउँपालिका	"},
    {"id": 331, "districtid": 31, "text": "Hetauda Up. Ma. Na. Pa.", "textNP": "हेटौडा उपमहानगरपालिका"},
    {"id": 332, "districtid": 31, "text": "Indrasarowar Ga. Pa.", "textNP": "इन्द्रसरोबर गाउँपालिका"},
    {"id": 333, "districtid": 31, "text": "Kailash Ga. Pa.", "textNP": "कैलाश गाउँपालिका"},
    {"id": 334, "districtid": 31, "text": "Makawanpurgadhi Ga. Pa.", "textNP": "मकवानपुरगढी गाउँपालिका"},
    {"id": 335, "districtid": 31, "text": "Manahari Ga. Pa.", "textNP": "मनहरी गाउँपालिका"},
    {"id": 336, "districtid": 31, "text": "Raksirang Ga. Pa.", "textNP": "राक्सिराङ्ग गाउँपालिका"},
    {"id": 337, "districtid": 31, "text": "Thaha Na. Pa.", "textNP": "थाहा नगरपालिका"},
    {"id": 338, "districtid": 32, "text": "Baudhimai Na. Pa.", "textNP": "बौधीमाई नगरपालिका"},
    {"id": 339, "districtid": 32, "text": "Brindaban Na. Pa.", "textNP": "बृन्दावन नगरपालिका"},
    {"id": 340, "districtid": 32, "text": "Chandrapur Na. Pa.", "textNP": "चन्द्रपुर नगरपालिका"},
    {"id": 341, "districtid": 32, "text": "Dewahhi Gonahi Na. Pa.", "textNP": "देवाही गोनाही नगरपालिका"},
    {"id": 342, "districtid": 32, "text": "Durga Bhagwati Ga. Pa.", "textNP": "दुर्गा भगवती गाउँपालिका"},
    {"id": 343, "districtid": 32, "text": "Gadhimai Na. Pa.", "textNP": "गढीमाई नगरपालिका"},
    {"id": 344, "districtid": 32, "text": "Garuda Na. Pa.", "textNP": "गरुडा नगरपालिका"},
    {"id": 345, "districtid": 32, "text": "Gaur Na. Pa.", "textNP": "गौर नगरपालिका"},
    {"id": 346, "districtid": 32, "text": "Gujara Na. Pa.", "textNP": "गुजरा नगरपालिका"},
    {"id": 347, "districtid": 32, "text": "Ishanath Na. Pa.", "textNP": "ईशनाथ नगरपालिका"},
    {"id": 348, "districtid": 32, "text": "Katahariya Na. Pa.", "textNP": "कटहरिया नगरपालिका"},
    {"id": 349, "districtid": 32, "text": "Madhav Narayan Na. Pa.", "textNP": "माधव नारायण नगरपालिका"},
    {"id": 350, "districtid": 32, "text": "Maulapur Na. Pa.", "textNP": "मौलापुर नगरपालिका"},
    {"id": 351, "districtid": 32, "text": "Paroha Na. Pa.", "textNP": "परोहा नगरपालिका"},
    {"id": 352, "districtid": 32, "text": "Phatuwa Bijayapur Na. Pa.", "textNP": "फतुवाबिजयपुर नगरपालिका"},
    {"id": 353, "districtid": 32, "text": "Rajdevi Na. Pa.", "textNP": "राजदेवी नगरपालिका"},
    {"id": 354, "districtid": 32, "text": "Rajpur Na. Pa.", "textNP": "राजपुर नगरपालिका"},
    {"id": 355, "districtid": 32, "text": "Yemunamai Ga. Pa.", "textNP": "यमुनामाई गाउँपालिका"},
    {"id": 356, "districtid": 33, "text": "Adarshkotwal Ga. Pa.", "textNP": "आदर्श कोटवाल गाउँपालिका"},
    {"id": 357, "districtid": 33, "text": "Baragadhi Ga. Pa.", "textNP": "बारागढीगाउँपालिका"},
    {"id": 358, "districtid": 33, "text": "Bishrampur Ga. Pa.", "textNP": "विश्रामपुर गाउँपालिका"},
    {"id": 359, "districtid": 33, "text": "Devtal Ga. Pa.", "textNP": "देवताल गाउँपालिका"},
    {"id": 360, "districtid": 33, "text": "Jitpur Simara Up. Ma. Na. Pa.", "textNP": "जीतपुर सिमरा उपमहानगरपालिका"},
    {"id": 361, "districtid": 33, "text": "Kalaiya Up. Ma. Na. Pa.", "textNP": "कलैया उपमहानगरपालिका"},
    {"id": 362, "districtid": 33, "text": "Karaiyamai Ga. Pa.", "textNP": "करैयामाई गाउँपालिका"},
    {"id": 363, "districtid": 33, "text": "Kolhabi Na. Pa.", "textNP": "कोल्हवी नगरपालिका"},
    {"id": 364, "districtid": 33, "text": "Mahagadhimai Na. Pa.", "textNP": "महागढीमाई नगरपालिका"},
    {"id": 365, "districtid": 33, "text": "Nijgadh Na. Pa.", "textNP": "निजगढ नगरपालिका"},
    {"id": 366, "districtid": 33, "text": "Pacharauta Na. Pa.", "textNP": "पचरौता नगरपालिका"},
    {"id": 367, "districtid": 33, "text": "Parwanipur Ga. Pa.", "textNP": "परवानीपुर गाउँपालिका"},
    {"id": 368, "districtid": 33, "text": "Pheta Ga. Pa.", "textNP": "फेटा गाउँपालिका"},
    {"id": 369, "districtid": 33, "text": "Prasauni Ga. Pa.", "textNP": "प्रसौनी गाउँपालिका"},
    {"id": 370, "districtid": 33, "text": "Simraungadh Na. Pa.", "textNP": "सिम्रौनगढ नगरपालिका"},
    {"id": 371, "districtid": 33, "text": "Suwarna Ga. Pa.", "textNP": "सुवर्ण गाउँपालिका"},
    {"id": 372, "districtid": 34, "text": "Bahudaramai Na. Pa.", "textNP": "बहुदरमाई नगरपालिका"},
    {"id": 373, "districtid": 34, "text": "Bindabasini Ga. Pa.", "textNP": "बिन्दबासिनी गाउँपालिका"},
    {"id": 374, "districtid": 34, "text": "Birgunj Ma. Na. Pa.", "textNP": "बिरगंज महानगरपालिका"},
    {"id": 375, "districtid": 34, "text": "Chhipaharmai Ga. Pa.", "textNP": "छिपहरमाई गाउँपालिका"},
    {"id": 376, "districtid": 34, "text": "Dhobini Ga. Pa.", "textNP": "धोबीनी गाउँपालिका"},
    {"id": 377, "districtid": 34, "text": "Jagarnathpur Ga. Pa.", "textNP": "जगरनाथपुर गाउँपालिका"},
    {"id": 378, "districtid": 34, "text": "Jirabhawani Ga. Pa.", "textNP": "जिरा भवानी गाउँपालिका"},
    {"id": 379, "districtid": 34, "text": "Kalikamai Ga. Pa.", "textNP": "कालिकामाई गाउँपालिका"},
    {"id": 380, "districtid": 34, "text": "Pakahamainpur Ga. Pa.", "textNP": "पकाहा मैनपुर गाउँपालिका"},
    {"id": 381, "districtid": 34, "text": "Parsagadhi Na. Pa.", "textNP": "पर्सागढी नगरपालिका"},
    {"id": 382, "districtid": 34, "text": "Paterwasugauli Ga. Pa.", "textNP": "पटेर्वा सुगौली गाउँपालिका"},
    {"id": 383, "districtid": 34, "text": "Pokhariya Na. Pa.", "textNP": "पोखरिया नगरपालिका"},
    {"id": 384, "districtid": 34, "text": "SakhuwaPrasauni Ga. Pa.", "textNP": "सखुवा प्रसौनी गाउँपालिका"},
    {"id": 385, "districtid": 34, "text": "Thori Ga. Pa.", "textNP": "ठोरी गाउँपालिका"},
    {"id": 386, "districtid": 35, "text": "Bharatpur Ma. Na. Pa.", "textNP": "भरतपुर महानगरपालिका"},
    {"id": 387, "districtid": 35, "text": "Ichchhyakamana Ga. Pa.", "textNP": "इच्छाकामना गाउँपालिका"},
    {"id": 388, "districtid": 35, "text": "Kalika Na. Pa.", "textNP": "कालिका नगरपालिका"},
    {"id": 389, "districtid": 35, "text": "Khairahani Na. Pa.", "textNP": "खैरहनी नगरपालिका"},
    {"id": 390, "districtid": 35, "text": "Madi Na. Pa.", "textNP": "माडी नगरपालिका"},
    {"id": 391, "districtid": 35, "text": "Rapti Na. Pa.", "textNP": "राप्ती नगरपालिका"},
    {"id": 392, "districtid": 35, "text": "Ratnanagar Na. Pa.", "textNP": "रत्ननगर नगरपालिका"},
    {"id": 393, "districtid": 36, "text": "Aarughat Ga. Pa.", "textNP": "आरूघाट गाउँपालिका"},
    {"id": 394, "districtid": 36, "text": "Ajirkot Ga. Pa.", "textNP": "अजिरकोट गाउँपालिका"},
    {"id": 395, "districtid": 36, "text": "Bhimsen Ga. Pa.", "textNP": "भिमसेनथापा गाउँपालिका"},
    {"id": 396, "districtid": 36, "text": "Chum Nubri Ga. Pa.", "textNP": "चुमनुव्री गाउँपालिका"},
    {"id": 397, "districtid": 36, "text": "Dharche Ga. Pa.", "textNP": "धार्चे गाउँपालिका"},
    {"id": 398, "districtid": 36, "text": "Gandaki Ga. Pa.", "textNP": "गण्डकी गाउँपालिका"},
    {"id": 399, "districtid": 36, "text": "Gorkha Na. Pa.", "textNP": "गोरखा नगरपालिका"},
    {"id": 400, "districtid": 36, "text": "Palungtar Na. Pa.", "textNP": "पालुङटार नगरपालिका"},
    {"id": 401, "districtid": 36, "text": "Sahid Lakhan Ga. Pa.", "textNP": "शहिद लखन गाउँपालिका"},
    {"id": 402, "districtid": 36, "text": "Siranchok Ga. Pa.", "textNP": "सिरानचोक गाउँपालिका"},
    {"id": 403, "districtid": 36, "text": "Sulikot Ga. Pa.", "textNP": "बारपाक सुलिकोट गाउँपालिका"},
    {"id": 404, "districtid": 37, "text": "Besishahar Na. Pa.", "textNP": "बेसीशहर नगरपालिका"},
    {"id": 405, "districtid": 37, "text": "Dordi Ga. Pa.", "textNP": "दोर्दी गाउँपालिका"},
    {"id": 406, "districtid": 37, "text": "Dudhpokhari Ga. Pa.", "textNP": "दूधपोखरी गाउँपालिका"},
    {"id": 407, "districtid": 37, "text": "Kwholasothar Ga. Pa.", "textNP": "क्व्होलासोथार गाउँपालिका"},
    {"id": 408, "districtid": 37, "text": "MadhyaNepal Na. Pa.", "textNP": "मध्यनेपाल नगरपालिका"},
    {"id": 409, "districtid": 37, "text": "Marsyangdi Ga. Pa.", "textNP": "मर्स्याङदी गाउँपालिका"},
    {"id": 410, "districtid": 37, "text": "Rainas Na. Pa.", "textNP": "मर्स्याङदी गाउँपालिका"},
    {"id": 411, "districtid": 37, "text": "Sundarbazar Na. Pa.", "textNP": "रार्इनास नगरपालिका"},
    {"id": 412, "districtid": 38, "text": "Anbukhaireni Ga. Pa.", "textNP": "आँबुखैरेनी गाउँपालिका"},
    {"id": 413, "districtid": 38, "text": "Bandipur Ga. Pa.", "textNP": "वन्दिपुर गाउँपालिका"},
    {"id": 414, "districtid": 38, "text": "Bhanu Na. Pa.", "textNP": "भानु नगरपालिका"},
    {"id": 415, "districtid": 38, "text": "Bhimad Na. Pa.", "textNP": "भिमाद नगरपालिका"},
    {"id": 416, "districtid": 38, "text": "Byas Na. Pa.", "textNP": "व्यास नगरपालिका"},
    {"id": 417, "districtid": 38, "text": "Devghat Ga. Pa.", "textNP": "देवघाट गाउँपालिका"},
    {"id": 418, "districtid": 38, "text": "Ghiring Ga. Pa.", "textNP": "घिरिङ गाउँपालिका"},
    {"id": 419, "districtid": 38, "text": "Myagde Ga. Pa.", "textNP": "म्याग्दे गाउँपालिका"},
    {"id": 420, "districtid": 38, "text": "Rhishing Ga. Pa.", "textNP": "ऋषिङ्ग गाउँपालिका"},
    {"id": 421, "districtid": 38, "text": "Shuklagandaki Na. Pa.", "textNP": "शुक्लागण्डकी नगरपालिका"},
    {"id": 422, "districtid": 39, "text": "Aandhikhola Ga. Pa.", "textNP": "आँधिखोला गाउँपालिका"},
    {"id": 423, "districtid": 39, "text": "Arjunchaupari Ga. Pa.", "textNP": "अर्जुनचौपारी गाउँपालिका"},
    {"id": 424, "districtid": 39, "text": "Bhirkot Na. Pa.", "textNP": "भीरकोट नगरपालिका"},
    {"id": 425, "districtid": 39, "text": "Biruwa Ga. Pa.", "textNP": "बिरुवा गाउँपालिका"},
    {"id": 426, "districtid": 39, "text": "Chapakot Na. Pa.", "textNP": "चापाकोट नगरपालिका"},
    {"id": 427, "districtid": 39, "text": "Galyang Na. Pa.", "textNP": "गल्याङ नगरपालिका"},
    {"id": 428, "districtid": 39, "text": "Harinas Ga. Pa.", "textNP": "हरिनास गाउँपालिका"},
    {"id": 429, "districtid": 39, "text": "Kaligandagi Ga. Pa.", "textNP": "कालीगण्डकी गाउँपालिका"},
    {"id": 430, "districtid": 39, "text": "Phedikhola Ga. Pa.", "textNP": "फेदीखोला गाउँपालिका"},
    {"id": 431, "districtid": 39, "text": "Putalibazar Na. Pa.", "textNP": "पुतलीबजार नगरपालिका"},
    {"id": 432, "districtid": 39, "text": "Waling Na. Pa.", "textNP": "वालिङ नगरपालिका"},
    {"id": 433, "districtid": 40, "text": "Annapurna Ga. Pa.", "textNP": "अन्नपूर्ण गाउँपालिका"},
    {"id": 434, "districtid": 40, "text": "Machhapuchchhre Ga. Pa.", "textNP": "माछापुच्छ्रे गाउँपालिका"},
    {"id": 435, "districtid": 40, "text": "Madi Ga. Pa.", "textNP": "मादी गाउँपालिका"},
    {"id": 436, "districtid": 40, "text": "Pokhara Lekhnath Ma. Na. Pa.", "textNP": "पोखरा महानगरपालिका"},
    {"id": 437, "districtid": 40, "text": "Rupa Ga. Pa.", "textNP": "रूपा गाउँपालिका"},
    {"id": 438, "districtid": 41, "text": "Chame Ga. Pa.", "textNP": "चामे गाउँपालिका"},
    {"id": 439, "districtid": 41, "text": "Narphu Ga. Pa.", "textNP": "नार्पा भूमि गाउँपालिका"},
    {"id": 440, "districtid": 41, "text": "Nashong Ga. Pa.", "textNP": "नासोँ गाउँपालिका"},
    {"id": 441, "districtid": 41, "text": "Neshyang Ga. Pa.", "textNP": "मनाङ ङिस्याङ गाउँपालिका"},
    {"id": 442, "districtid": 42, "text": "Barhagaun Muktikhsetra Ga. Pa.", "textNP": "वारागुङ मुक्तिक्षेत्र गाउँपालिका"},
    {"id": 443, "districtid": 42, "text": "Dalome Ga. Pa.", "textNP": "लो-घेकर दामोदरकुण्ड गाउँपालिका"},
    {"id": 444, "districtid": 42, "text": "Gharapjhong Ga. Pa.", "textNP": "घरपझोङ गाउँपालिका"},
    {"id": 445, "districtid": 42, "text": "Lomanthang Ga. Pa.", "textNP": "लोमन्थाङ गाउँपालिका"},
    {"id": 446, "districtid": 42, "text": "Thasang Ga. Pa.", "textNP": "थासाङ गाउँपालिका"},
    {"id": 447, "districtid": 43, "text": "Bihadi Ga. Pa.", "textNP": "विहादी गाउँपालिका"},
    {"id": 448, "districtid": 43, "text": "Jaljala Ga. Pa.", "textNP": "जलजला गाउँपालिका"},
    {"id": 449, "districtid": 43, "text": "Kushma Na. Pa.", "textNP": "कुश्मा नगरपालिका"},
    {"id": 450, "districtid": 43, "text": "Mahashila Ga. Pa.", "textNP": "महाशिला गाउँपालिका"},
    {"id": 451, "districtid": 43, "text": "Modi Ga. Pa.", "textNP": "मोदी गाउँपालिका"},
    {"id": 452, "districtid": 43, "text": "Painyu Ga. Pa.", "textNP": "पैयूं गाउँपालिका"},
    {"id": 453, "districtid": 43, "text": "Phalebas Na. Pa.", "textNP": "फलेवास नगरपालिका"},
    {"id": 454, "districtid": 44, "text": "Annapurna Ga. Pa.", "textNP": "अन्नपुर्ण गाउँपालिका"},
    {"id": 455, "districtid": 44, "text": "Beni Na. Pa.", "textNP": "बेनी नगरपालिका"},
    {"id": 456, "districtid": 44, "text": "Dhaulagiri Ga. Pa.", "textNP": "धवलागिरी गाउँपालिका"},
    {"id": 457, "districtid": 44, "text": "Malika Ga. Pa.", "textNP": "मालिका गाउँपालिका"},
    {"id": 458, "districtid": 44, "text": "Mangala Ga. Pa.", "textNP": "मंगला गाउँपालिका"},
    {"id": 459, "districtid": 44, "text": "Raghuganga Ga. Pa.", "textNP": "रघुगंगा गाउँपालिका"},
    {"id": 460, "districtid": 45, "text": "Badigad Ga. Pa.", "textNP": "वडिगाड गाउँपालिका"},
    {"id": 461, "districtid": 45, "text": "Baglung Na. Pa.", "textNP": "बागलुङ नगरपालिका"},
    {"id": 462, "districtid": 45, "text": "Bareng Ga. Pa.", "textNP": "वरेङ गाउँपालिका"},
    {"id": 463, "districtid": 45, "text": "Dhorpatan Na. Pa.", "textNP": "ढोरपाटन नगरपालिका"},
    {"id": 464, "districtid": 45, "text": "Galkot Na. Pa.", "textNP": "गल्कोट नगरपालिका"},
    {"id": 465, "districtid": 45, "text": "Jaimuni Na. Pa.", "textNP": "जैमूनी नगरपालिका"},
    {"id": 466, "districtid": 45, "text": "Kanthekhola Ga. Pa.", "textNP": "काठेखोला गाउँपालिका"},
    {"id": 467, "districtid": 45, "text": "Nisikhola Ga. Pa.", "textNP": "निसीखोला गाउँपालिका"},
    {"id": 468, "districtid": 45, "text": "Taman Khola Ga. Pa.", "textNP": "तमानखोला गाउँपालिका"},
    {"id": 469, "districtid": 45, "text": "Tara Khola Ga. Pa.", "textNP": "ताराखोला गाउँपालिका"},
    {"id": 470, "districtid": 46, "text": "Chandrakot Ga. Pa.", "textNP": "चन्द्रकोट गाउँपालिका"},
    {"id": 471, "districtid": 46, "text": "Chatrakot Ga. Pa.", "textNP": "छत्रकोट गाउँपालिका"},
    {"id": 472, "districtid": 46, "text": "Dhurkot Ga. Pa.", "textNP": "धुर्कोट गाउँपालिका"},
    {"id": 473, "districtid": 46, "text": "Gulmidarbar Ga. Pa.", "textNP": "गुल्मी दरबार गाउँपालिका"},
    {"id": 474, "districtid": 46, "text": "Isma Ga. Pa.", "textNP": "ईस्मा गाउँपालिका"},
    {"id": 475, "districtid": 46, "text": "Kaligandaki Ga. Pa.", "textNP": "कालीगण्डकी गाउँपालिका"},
    {"id": 476, "districtid": 46, "text": "Madane Ga. Pa.", "textNP": "मदाने गाउँपालिका"},
    {"id": 477, "districtid": 46, "text": "Malika Ga. Pa.", "textNP": "मालिका गाउँपालिका"},
    {"id": 478, "districtid": 46, "text": "Musikot Na. Pa.", "textNP": "मुसिकोट नगरपालिका"},
    {"id": 479, "districtid": 46, "text": "Resunga Na. Pa.", "textNP": "रेसुङ्गा नगरपालिका"},
    {"id": 480, "districtid": 46, "text": "Ruru Ga. Pa.", "textNP": "रुरुक्षेत्र गाउँपालिका"},
    {"id": 481, "districtid": 46, "text": "Satyawati Ga. Pa.", "textNP": "सत्यवती गाउँपालिका"},
    {"id": 482, "districtid": 47, "text": "Bagnaskali Ga. Pa.", "textNP": "बगनासकाली गाउँपालिका"},
    {"id": 483, "districtid": 47, "text": "Mathagadhi Ga. Pa.", "textNP": "माथागढी गाउँपालिका"},
    {"id": 484, "districtid": 47, "text": "Nisdi Ga. Pa.", "textNP": "निस्दी गाउँपालिका"},
    {"id": 485, "districtid": 47, "text": "Purbakhola Ga. Pa.", "textNP": "पूर्वखोला गाउँपालिका"},
    {"id": 486, "districtid": 47, "text": "Rainadevi Chhahara Ga. Pa.", "textNP": "रैनादेवी छहरा गाउँपालिका"},
    {"id": 487, "districtid": 47, "text": "Rambha Ga. Pa.", "textNP": "रम्भा गाउँपालिका"},
    {"id": 488, "districtid": 47, "text": "Rampur Na. Pa.", "textNP": "रामपुर नगरपालिका"},
    {"id": 489, "districtid": 47, "text": "Ribdikot Ga. Pa.", "textNP": "रिब्दिकोट गाउँपालिका"},
    {"id": 490, "districtid": 47, "text": "Tansen Na. Pa.", "textNP": "तानसेन नगरपालिका"},
    {"id": 491, "districtid": 47, "text": "Tinau Ga. Pa.", "textNP": "तिनाउ गाउँपालिका"},
    {"id": 492, "districtid": 48, "text": "Bardaghat Na. Pa.", "textNP": "बर्दघाट नगरपालिका"},
    {"id": 493, "districtid": 48, "text": "Palhi Nandan Ga. Pa.", "textNP": "पाल्हीनन्दन गाउँपालिका"},
    {"id": 494, "districtid": 48, "text": "Pratappur Ga. Pa.", "textNP": "प्रतापपुर गाउँपालिका"},
    {"id": 495, "districtid": 48, "text": "Ramgram Na. Pa.", "textNP": "रामग्राम नगरपालिका"},
    {"id": 496, "districtid": 48, "text": "Sarawal Ga. Pa.", "textNP": "सरावल गाउँपालिका"},
    {"id": 497, "districtid": 48, "text": "Sunwal Na. Pa.", "textNP": "सुनवल नगरपालिका"},
    {"id": 498, "districtid": 48, "text": "Susta Ga. Pa.", "textNP": "सुस्ता गाउँपालिका"},
    {"id": 499, "districtid": 49, "text": "Binayee Tribeni Ga. Pa.", "textNP": "विनयी त्रिवेणी गाउँपालिका"},
    {"id": 500, "districtid": 49, "text": "Bulingtar Ga. Pa.", "textNP": "बुलिङटार गाउँपालिका"},
    {"id": 501, "districtid": 49, "text": "Bungdikali Ga. Pa.", "textNP": "बौदीकाली गाउँपालिका"},
    {"id": 502, "districtid": 49, "text": "Devchuli Na. Pa.", "textNP": "देवचुली नगरपालिका"},
    {"id": 503, "districtid": 49, "text": "Gaidakot Na. Pa.", "textNP": "गैडाकोट नगरपालिका"},
    {"id": 504, "districtid": 49, "text": "Hupsekot Ga. Pa.", "textNP": "हुप्सेकोट गाउँपालिका"},
    {"id": 505, "districtid": 49, "text": "Kawasoti Na. Pa.", "textNP": "कावासोती नगरपालिका"},
    {"id": 506, "districtid": 49, "text": "Madhyabindu Na. Pa.", "textNP": "मध्यविन्दु नगरपालिका"},
    {"id": 507, "districtid": 50, "text": "Butwal Up. Ma. Na. Pa.", "textNP": "बुटवल उपमहानगरपालिका"},
    {"id": 508, "districtid": 50, "text": "Devdaha Na. Pa.", "textNP": "देवदह नगरपालिका"},
    {"id": 509, "districtid": 50, "text": "Gaidahawa Ga. Pa.", "textNP": "गैडहवा गाउँपालिका"},
    {"id": 510, "districtid": 50, "text": "Kanchan Ga. Pa.", "textNP": "कन्चन गाउँपालिका"},
    {"id": 511, "districtid": 50, "text": "Kotahimai Ga. Pa.", "textNP": "कोटहीमाई गाउँपालिका"},
    {"id": 512, "districtid": 50, "text": "Lumbini Sanskritik Na. Pa.", "textNP": "लुम्बिनी सांस्कृतिक नगरपालिका"},
    {"id": 513, "districtid": 50, "text": "Marchawari Ga. Pa.", "textNP": "मर्चवारी गाउँपालिका"},
    {"id": 514, "districtid": 50, "text": "Mayadevi Ga. Pa.", "textNP": "मायादेवी गाउँपालिका"},
    {"id": 515, "districtid": 50, "text": "Omsatiya Ga. Pa.", "textNP": "ओमसतिया गाउँपालिका"},
    {"id": 516, "districtid": 50, "text": "Rohini Ga. Pa.", "textNP": "रोहिणी गाउँपालिका"},
    {"id": 517, "districtid": 50, "text": "Sainamaina Na. Pa.", "textNP": "सैनामैना नगरपालिका"},
    {"id": 518, "districtid": 50, "text": "Sammarimai Ga. Pa.", "textNP": "सम्मरीमाई गाउँपालिका"},
    {"id": 519, "districtid": 50, "text": "Siddharthanagar Na. Pa.", "textNP": "सिद्धार्थनगर नगरपालिका"},
    {"id": 520, "districtid": 50, "text": "Siyari Ga. Pa.", "textNP": "सियारी गाउँपालिका"},
    {"id": 521, "districtid": 50, "text": "Sudhdhodhan Ga. Pa.", "textNP": "शुद्धोधन गाउँपालिका"},
    {"id": 522, "districtid": 50, "text": "Tillotama Na. Pa.", "textNP": "तिलोत्तमा नगरपालिका"},
    {"id": 523, "districtid": 51, "text": "Bhumekasthan Na. Pa.", "textNP": "भूमिकास्थान नगरपालिका"},
    {"id": 524, "districtid": 51, "text": "Chhatradev Ga. Pa.", "textNP": "छत्रदेव गाउँपालिका"},
    {"id": 525, "districtid": 51, "text": "Malarani Ga. Pa.", "textNP": "मालारानी गाउँपालिका"},
    {"id": 526, "districtid": 51, "text": "Panini Ga. Pa.", "textNP": "पाणिनी गाउँपालिका"},
    {"id": 527, "districtid": 51, "text": "Sandhikharka Na. Pa.", "textNP": "सन्धिखर्क नगरपालिका"},
    {"id": 528, "districtid": 51, "text": "Sitganga Na. Pa.", "textNP": "शितगंगा नगरपालिका"},
    {"id": 529, "districtid": 52, "text": "Banganga Na. Pa.", "textNP": "बाणगंगा नगरपालिका"},
    {"id": 530, "districtid": 52, "text": "Bijayanagar Ga. Pa.", "textNP": "विजयनगर गाउँपालिका"},
    {"id": 531, "districtid": 52, "text": "Buddhabhumi Na. Pa.", "textNP": "बुद्धभुमी नगरपालिका"},
    {"id": 532, "districtid": 52, "text": "Kapilbastu Na. Pa.", "textNP": "कपिलवस्तु नगरपालिका"},
    {"id": 533, "districtid": 52, "text": "Krishnanagar Na. Pa.", "textNP": "कृष्णनगर नगरपालिका"},
    {"id": 534, "districtid": 52, "text": "Maharajgunj Na. Pa.", "textNP": "महाराजगंज नगरपालिका"},
    {"id": 535, "districtid": 52, "text": "Mayadevi Ga. Pa.", "textNP": "मायादेवी गाउँपालिका"},
    {"id": 536, "districtid": 52, "text": "Shivaraj Na. Pa.", "textNP": "शिवराज नगरपालिका"},
    {"id": 537, "districtid": 52, "text": "Suddhodhan Ga. Pa.", "textNP": "सुद्धोधन गाउँपालिका"},
    {"id": 538, "districtid": 52, "text": "Yashodhara Ga. Pa.", "textNP": "यसोधरा गाउँपालिका"},
    {"id": 539, "districtid": 53, "text": "Ayirabati Ga. Pa.", "textNP": "ऐरावती गाउँपालिका"},
    {"id": 540, "districtid": 53, "text": "Gaumukhi Ga. Pa.", "textNP": "गौमुखी गाउँपालिका"},
    {"id": 541, "districtid": 53, "text": "Jhimruk Ga. Pa.", "textNP": "झिमरुक गाउँपालिका"},
    {"id": 542, "districtid": 53, "text": "Mallarani Ga. Pa.", "textNP": "मल्लरानी गाउँपालिका"},
    {"id": 543, "districtid": 53, "text": "Mandavi Ga. Pa.", "textNP": "माण्डवी गाउँपालिका"},
    {"id": 544, "districtid": 53, "text": "Naubahini Ga. Pa.", "textNP": "नौवहिनी गाउँपालिका"},
    {"id": 545, "districtid": 53, "text": "Pyuthan Na. Pa.", "textNP": "प्यूठान नगरपालिका"},
    {"id": 546, "districtid": 53, "text": "Sarumarani Ga. Pa.", "textNP": "सरुमारानी गाउँपालिका"},
    {"id": 547, "districtid": 53, "text": "Sworgadwary Na. Pa.", "textNP": "स्वर्गद्वारी नगरपालिका"},
    {"id": 548, "districtid": 54, "text": "Duikholi Ga. Pa.", "textNP": "परिवर्तन गाउँपालिका"},
    {"id": 549, "districtid": 54, "text": "Lungri Ga. Pa.", "textNP": "लुङग्री गाउँपालिका"},
    {"id": 550, "districtid": 54, "text": "Madi Ga. Pa.", "textNP": "माडी गाउँपालिका"},
    {"id": 551, "districtid": 54, "text": "Rolpa Na. Pa.", "textNP": "रोल्पा नगरपालिका"},
    {"id": 552, "districtid": 54, "text": "Runtigadi Ga. Pa.", "textNP": "रुन्टीगढी गाउँपालिका"},
    {"id": 553, "districtid": 54, "text": "Sukidaha Ga. Pa.", "textNP": "गंगादेव गाउँपालिका"},
    {"id": 554, "districtid": 54, "text": "Sunchhahari Ga. Pa.", "textNP": "सुनछहरी गाउँपालिका"},
    {"id": 555, "districtid": 54, "text": "Suwarnabati Ga. Pa.", "textNP": "सुनिल स्मृति गाउँपालिका"},
    {"id": 556, "districtid": 54, "text": "Thawang Ga. Pa.", "textNP": "थवाङ गाउँपालिका"},
    {"id": 557, "districtid": 54, "text": "Tribeni Ga. Pa.", "textNP": "त्रिवेणी गाउँपालिका"},
    {"id": 558, "districtid": 55, "text": "Aathbiskot Na. Pa.", "textNP": "आठबिसकोट नगरपालिका"},
    {"id": 559, "districtid": 55, "text": "Banfikot Ga. Pa.", "textNP": "बाँफिकोट गाउँपालिका"},
    {"id": 560, "districtid": 55, "text": "Chaurjahari Na. Pa.", "textNP": "चौरजहारी नगरपालिका"},
    {"id": 561, "districtid": 55, "text": "Musikot Na. Pa.", "textNP": "मुसिकोट नगरपालिका"},
    {"id": 562, "districtid": 55, "text": "Sani Bheri Ga. Pa.", "textNP": "सानी भेरी गाउँपालिका"},
    {"id": 563, "districtid": 55, "text": "Tribeni Ga. Pa.", "textNP": "त्रिवेणी गाउँपालिका"},
    {"id": 564, "districtid": 56, "text": "Bhume Ga. Pa.", "textNP": "भूमे गाउँपालिका"},
    {"id": 565, "districtid": 56, "text": "Putha Uttarganga Ga. Pa.", "textNP": "पुथा उत्तरगंगा गाउँपालिका"},
    {"id": 566, "districtid": 56, "text": "Sisne Ga. Pa.", "textNP": "सिस्ने गाउँपालिका"},
    {"id": 567, "districtid": 57, "text": "Bagchaur Na. Pa.", "textNP": "बागचौर नगरपालिका"},
    {"id": 568, "districtid": 57, "text": "Bangad Kupinde Na. Pa.", "textNP": "बनगाड कुपिण्डे नगरपालिका"},
    {"id": 569, "districtid": 57, "text": "Chhatreshwori Ga. Pa.", "textNP": "छत्रेश्वरी गाउँपालिका"},
    {"id": 570, "districtid": 57, "text": "Darma Ga. Pa.", "textNP": "दार्मा गाउँपालिका"},
    {"id": 571, "districtid": 57, "text": "Siddha Kumakh Ga. Pa.", "textNP": "सिद्ध कुमाख गाउँपालिका"},
    {"id": 572, "districtid": 57, "text": "Kalimati Ga. Pa.", "textNP": "कालिमाटी गाउँपालिका"},
    {"id": 573, "districtid": 57, "text": "Kapurkot Ga. Pa.", "textNP": "कपुरकोट गाउँपालिका"},
    {"id": 574, "districtid": 57, "text": "Kumakhmalika Ga. Pa.", "textNP": "कुमाख गाउँपालिका"},
    {"id": 575, "districtid": 57, "text": "Sharada Na. Pa.", "textNP": "शारदा नगरपालिका"},
    {"id": 576, "districtid": 57, "text": "Tribeni Ga. Pa.", "textNP": "त्रिवेणी गाउँपालिका"},
    {"id": 577, "districtid": 58, "text": "Babai Ga. Pa.", "textNP": "बबई गाउँपालिका"},
    {"id": 578, "districtid": 58, "text": "Banglachuli Ga. Pa.", "textNP": "बंगलाचुली गाउँपालिका"},
    {"id": 579, "districtid": 58, "text": "Dangisharan Ga. Pa.", "textNP": "दंगीशरण गाउँपालिका"},
    {"id": 580, "districtid": 58, "text": "Gadhawa Ga. Pa.", "textNP": "गढवा गाउँपालिका"},
    {"id": 581, "districtid": 58, "text": "Ghorahi Up. Ma. Na. Pa.", "textNP": "घोराही उपमहानगरपालिका"},
    {"id": 582, "districtid": 58, "text": "Lamahi Na. Pa.", "textNP": "लमही नगरपालिका"},
    {"id": 583, "districtid": 58, "text": "Rajpur Ga. Pa.", "textNP": "राजपुर गाउँपालिका"},
    {"id": 584, "districtid": 58, "text": "Rapti Ga. Pa.", "textNP": "राप्ती गाउँपालिका"},
    {"id": 585, "districtid": 58, "text": "Shantinagar Ga. Pa.", "textNP": "शान्तिनगर गाउँपालिका"},
    {"id": 586, "districtid": 58, "text": "Tulsipur Up. Ma. Na. Pa.", "textNP": "तुल्सीपुर उपमहानगरपालिका"},
    {"id": 587, "districtid": 59, "text": "Badhaiyatal Ga. Pa.", "textNP": "बढैयाताल गाउँपालिका"},
    {"id": 588, "districtid": 59, "text": "Bansagadhi Na. Pa.", "textNP": "बाँसगढी नगरपालिका"},
    {"id": 589, "districtid": 59, "text": "Barbardiya Na. Pa.", "textNP": "बारबर्दिया नगरपालिका"},
    {"id": 590, "districtid": 59, "text": "Geruwa Ga. Pa.", "textNP": "गेरुवा गाउँपालिका"},
    {"id": 591, "districtid": 59, "text": "Gulariya Na. Pa.", "textNP": "गुलरिया नगरपालिका"},
    {"id": 592, "districtid": 59, "text": "Madhuwan Na. Pa.", "textNP": "मधुवन नगरपालिका"},
    {"id": 593, "districtid": 59, "text": "Rajapur Na. Pa.", "textNP": "राजापुर नगरपालिका"},
    {"id": 594, "districtid": 59, "text": "Thakurbaba Na. Pa.", "textNP": "ठाकुरबाबा नगरपालिका"},
    {"id": 595, "districtid": 60, "text": "Barahtal Ga. Pa.", "textNP": "बराहताल गाउँपालिका"},
    {"id": 596, "districtid": 60, "text": "Bheriganga Na. Pa.", "textNP": "भेरीगंगा नगरपालिका"},
    {"id": 597, "districtid": 60, "text": "Birendranagar Na. Pa.", "textNP": "बीरेन्द्रनगर नगरपालिका"},
    {"id": 598, "districtid": 60, "text": "Chaukune Ga. Pa.", "textNP": "चौकुने गाउँपालिका"},
    {"id": 599, "districtid": 60, "text": "Chingad Ga. Pa.", "textNP": "चिङ्गाड गाउँपालिका"},
    {"id": 600, "districtid": 60, "text": "Gurbhakot Na. Pa.", "textNP": "गुर्भाकोट नगरपालिका"},
    {"id": 601, "districtid": 60, "text": "Lekbeshi Na. Pa.", "textNP": "लेकवेशी नगरपालिका"},
    {"id": 602, "districtid": 60, "text": "Panchpuri Na. Pa.", "textNP": "पञ्चपुरी नगरपालिका"},
    {"id": 603, "districtid": 60, "text": "Simta Ga. Pa.", "textNP": "सिम्ता गाउँपालिका"},
    {"id": 604, "districtid": 61, "text": "Aathabis Na. Pa.", "textNP": "आठबीस नगरपालिका"},
    {"id": 605, "districtid": 61, "text": "Bhagawatimai Ga. Pa.", "textNP": "भगवतीमाई गाउँपालिका"},
    {"id": 606, "districtid": 61, "text": "Bhairabi Ga. Pa.", "textNP": "भैरवी गाउँपालिका"},
    {"id": 607, "districtid": 61, "text": "Chamunda Bindrasaini Na. Pa.", "textNP": "चामुण्डा विन्द्रासैनी नगरपालिका"},
    {"id": 608, "districtid": 61, "text": "Dullu Na. Pa.", "textNP": "दुल्लु नगरपालिका"},
    {"id": 609, "districtid": 61, "text": "Dungeshwor Ga. Pa.", "textNP": "डुंगेश्वर गाउँपालिका"},
    {"id": 610, "districtid": 61, "text": "Gurans Ga. Pa.", "textNP": "गुराँस गाउँपालिका"},
    {"id": 611, "districtid": 61, "text": "Mahabu Ga. Pa.", "textNP": "महावु गाउँपालिका"},
    {"id": 612, "districtid": 61, "text": "Narayan Na. Pa.", "textNP": "नारायण नगरपालिका"},
    {"id": 613, "districtid": 61, "text": "Naumule Ga. Pa.", "textNP": "नौमुले गाउँपालिका"},
    {"id": 614, "districtid": 61, "text": "Thantikandh Ga. Pa.", "textNP": "ठाँटीकाँध गाउँपालिका"},
    {"id": 615, "districtid": 62, "text": "Baijanath Ga. Pa.", "textNP": "बैजनाथ गाउँपालिका"},
    {"id": 616, "districtid": 62, "text": "Duduwa Ga. Pa.", "textNP": "डुडुवा गाउँपालिका"},
    {"id": 617, "districtid": 62, "text": "Janki Ga. Pa.", "textNP": "जानकी गाउँपालिका"},
    {"id": 618, "districtid": 62, "text": "Khajura Ga. Pa.", "textNP": "खजुरा गाउँपालिका"},
    {"id": 619, "districtid": 62, "text": "Kohalpur Na. Pa.", "textNP": "कोहलपुर नगरपालिका"},
    {"id": 620, "districtid": 62, "text": "Narainapur Ga. Pa.", "textNP": "नरैनापुर गाउँपालिका"},
    {"id": 621, "districtid": 62, "text": "Nepalgunj Up. Ma. Na. Pa.", "textNP": "नेपालगंज उपमहानगरपालिका"},
    {"id": 622, "districtid": 62, "text": "Rapti Sonari Ga. Pa.", "textNP": "राप्ती सोनारी गाउँपालिका"},
    {"id": 623, "districtid": 63, "text": "Barekot Ga. Pa.", "textNP": "बारेकोट गाउँपालिका"},
    {"id": 624, "districtid": 63, "text": "Bheri Na. Pa.", "textNP": "भेरी नगरपालिका"},
    {"id": 625, "districtid": 63, "text": "Chhedagad Na. Pa.", "textNP": "छेडागाड नगरपालिका"},
    {"id": 626, "districtid": 63, "text": "Junichande Ga. Pa.", "textNP": "जुनीचाँदे गाउँपालिका"},
    {"id": 627, "districtid": 63, "text": "Kuse Ga. Pa.", "textNP": "कुसे गाउँपालिका"},
    {"id": 628, "districtid": 63, "text": "Shiwalaya Ga. Pa.", "textNP": "शिवालय गाउँपालिका"},
    {"id": 629, "districtid": 63, "text": "Tribeni Nalagad Na. Pa.", "textNP": "नलगाड नगरपालिका"},
    {"id": 630, "districtid": 64, "text": "Chharka Tangsong Ga. Pa.", "textNP": "छार्का ताङसोङ गाउँपालिका"},
    {"id": 631, "districtid": 64, "text": "Dolpo Buddha Ga. Pa.", "textNP": "डोल्पो बुद्ध गाउँपालिका"},
    {"id": 632, "districtid": 64, "text": "Jagadulla Ga. Pa.", "textNP": "जगदुल्ला गाउँपालिका"},
    {"id": 633, "districtid": 64, "text": "Kaike Ga. Pa.", "textNP": "काईके गाउँपालिका"},
    {"id": 634, "districtid": 64, "text": "Mudkechula Ga. Pa.", "textNP": "मुड्केचुला गाउँपालिका"},
    {"id": 635, "districtid": 64, "text": "Shey Phoksundo Ga. Pa.", "textNP": "शे फोक्सुन्डो गाउँपालिका"},
    {"id": 636, "districtid": 64, "text": "Thuli Bheri Na. Pa.", "textNP": "ठूली भेरी नगरपालिका"},
    {"id": 637, "districtid": 64, "text": "Tripurasundari Na. Pa.", "textNP": "त्रिपुरासुन्दरी नगरपालिका"},
    {"id": 638, "districtid": 65, "text": "Adanchuli Ga. Pa.", "textNP": "अदानचुली गाउँपालिका"},
    {"id": 639, "districtid": 65, "text": "Chankheli Ga. Pa.", "textNP": "चंखेली गाउँपालिका"},
    {"id": 640, "districtid": 65, "text": "Kharpunath Ga. Pa.", "textNP": "खार्पुनाथ गाउँपालिका"},
    {"id": 641, "districtid": 65, "text": "Namkha Ga. Pa.", "textNP": "नाम्खा गाउँपालिका"},
    {"id": 642, "districtid": 65, "text": "Sarkegad Ga. Pa.", "textNP": "सर्केगाड गाउँपालिका"},
    {"id": 643, "districtid": 65, "text": "Simkot Ga. Pa.", "textNP": "सिमकोट गाउँपालिका"},
    {"id": 644, "districtid": 65, "text": "Tanjakot Ga. Pa.", "textNP": "ताँजाकोट गाउँपालिका"},
    {"id": 645, "districtid": 66, "text": "Subh Kalika Ga. Pa.", "textNP": "शुभ कालीका गाउँपालिका"},
    {"id": 646, "districtid": 66, "text": "Khandachakra Na. Pa.", "textNP": "खाँडाचक्र नगरपालिका"},
    {"id": 647, "districtid": 66, "text": "Mahawai Ga. Pa.", "textNP": "महावै गाउँपालिका"},
    {"id": 648, "districtid": 66, "text": "Naraharinath Ga. Pa.", "textNP": "नरहरिनाथ गाउँपालिका"},
    {"id": 649, "districtid": 66, "text": "Pachaljharana Ga. Pa.", "textNP": "पचालझरना गाउँपालिका"},
    {"id": 650, "districtid": 66, "text": "Palata Ga. Pa.", "textNP": "पलाता गाउँपालिका"},
    {"id": 651, "districtid": 66, "text": "Raskot Na. Pa.", "textNP": "रास्कोट नगरपालिका"},
    {"id": 652, "districtid": 66, "text": "Sanni Tribeni Ga. Pa.", "textNP": "सान्नी त्रिवेणी गाउँपालिका"},
    {"id": 653, "districtid": 66, "text": "Tilagufa Na. Pa.", "textNP": "तिलागुफा नगरपालिका"},
    {"id": 654, "districtid": 67, "text": "Chhayanath Rara Na. Pa.", "textNP": "छायाँनाथ रारा नगरपालिका"},
    {"id": 655, "districtid": 67, "text": "Khatyad Ga. Pa.", "textNP": "खत्याड गाउँपालिका"},
    {"id": 656, "districtid": 67, "text": "Mugum Karmarong Ga. Pa.", "textNP": "मुगुम कार्मारोंग गाउँपालिका"},
    {"id": 657, "districtid": 67, "text": "Soru Ga. Pa.", "textNP": "सोरु गाउँपालिका"},
    {"id": 658, "districtid": 68, "text": "Chandannath Na. Pa.", "textNP": "चन्दननाथ नगरपालिका"},
    {"id": 659, "districtid": 68, "text": "Guthichaur Ga. Pa.", "textNP": "गुठिचौर गाउँपालिका"},
    {"id": 660, "districtid": 68, "text": "Hima Ga. Pa.", "textNP": "हिमा गाउँपालिका"},
    {"id": 661, "districtid": 68, "text": "Kanakasundari Ga. Pa.", "textNP": "कनकासुन्दरी गाउँपालिका"},
    {"id": 662, "districtid": 68, "text": "Patrasi Ga. Pa.", "textNP": "पातारासी गाउँपालिका"},
    {"id": 663, "districtid": 68, "text": "Sinja Ga. Pa.", "textNP": "सिंजा गाउँपालिका"},
    {"id": 664, "districtid": 68, "text": "Tatopani Ga. Pa.", "textNP": "तातोपानी गाउँपालिका"},
    {"id": 665, "districtid": 68, "text": "Tila Ga. Pa.", "textNP": "तिला गाउँपालिका"},
    {"id": 666, "districtid": 69, "text": "Badimalika Na. Pa.", "textNP": "बडीमालिका नगरपालिका"},
    {"id": 667, "districtid": 69, "text": "Budhiganga Na. Pa.", "textNP": "बुढीगंगा नगरपालिका"},
    {"id": 668, "districtid": 69, "text": "Budhinanda Na. Pa.", "textNP": "बुढीनन्दा नगरपालिका"},
    {"id": 669, "districtid": 69, "text": "Chhededaha Ga. Pa.", "textNP": "खप्तड छेडेदह गाउँपालिका"},
    {"id": 670, "districtid": 69, "text": "Gaumul Ga. Pa.", "textNP": "गौमुल गाउँपालिका"},
    {"id": 671, "districtid": 69, "text": "Himali Ga. Pa.", "textNP": "हिमाली गाउँपालिका"},
    {"id": 672, "districtid": 69, "text": "Jagannath Ga. Pa.", "textNP": "जगन्‍नाथ गाउँपालिका"},
    {"id": 673, "districtid": 69, "text": "Swami Kartik Ga. Pa.", "textNP": "स्वामीकार्तिक खापर गाउँपालिका"},
    {"id": 674, "districtid": 69, "text": "Tribeni Na. Pa.", "textNP": "त्रिवेणी नगरपालिका"},
    {"id": 675, "districtid": 70, "text": "Bithadchir Ga. Pa.", "textNP": "वित्थडचिर गाउँपालिका"},
    {"id": 676, "districtid": 70, "text": "Bungal Na. Pa.", "textNP": "बुंगल नगरपालिका"},
    {"id": 677, "districtid": 70, "text": "Chabispathivera Ga. Pa.", "textNP": "छबिसपाथिभेरा गाउँपालिका"},
    {"id": 678, "districtid": 70, "text": "Durgathali Ga. Pa.", "textNP": "दुर्गाथली गाउँपालिका"},
    {"id": 679, "districtid": 70, "text": "JayaPrithivi Na. Pa.", "textNP": "जयपृथ्वी नगरपालिका"},
    {"id": 680, "districtid": 70, "text": "Kanda Ga. Pa.", "textNP": "साइपाल गाउँपालिका"},
    {"id": 681, "districtid": 70, "text": "Kedarseu Ga. Pa.", "textNP": "केदारस्युँ गाउँपालिका"},
    {"id": 682, "districtid": 70, "text": "Khaptadchhanna Ga. Pa.", "textNP": "खप्तडछान्ना गाउँपालिका"},
    {"id": 683, "districtid": 70, "text": "Masta Ga. Pa.", "textNP": "मष्टा गाउँपालिका"},
    {"id": 684, "districtid": 70, "text": "Surma Ga. Pa.", "textNP": "सूर्मा गाउँपालिका"},
    {"id": 685, "districtid": 70, "text": "Talkot Ga. Pa.", "textNP": "तलकोट गाउँपालिका"},
    {"id": 686, "districtid": 70, "text": "Thalara Ga. Pa.", "textNP": "थलारा गाउँपालिका"},
    {"id": 687, "districtid": 71, "text": "Bannigadhi Jayagadh Ga. Pa.", "textNP": "बान्निगढी जयगढ गाउँपालिका"},
    {"id": 688, "districtid": 71, "text": "Chaurpati Ga. Pa.", "textNP": "चौरपाटी गाउँपालिका"},
    {"id": 689, "districtid": 71, "text": "Dhakari Ga. Pa.", "textNP": "ढकारी गाउँपालिका"},
    {"id": 690, "districtid": 71, "text": "Kamalbazar Na. Pa.", "textNP": "कमलबजार नगरपालिका"},
    {"id": 691, "districtid": 71, "text": "Mangalsen Na. Pa.", "textNP": "मंगलसेन नगरपालिका"},
    {"id": 692, "districtid": 71, "text": "Mellekh Ga. Pa.", "textNP": "मेल्लेख गाउँपालिका"},
    {"id": 693, "districtid": 71, "text": "Panchadewal Binayak Na. Pa.", "textNP": "पन्चदेवल विनायक नगरपालिका"},
    {"id": 694, "districtid": 71, "text": "Ramaroshan Ga. Pa.", "textNP": "रामारोशन गाउँपालिका"},
    {"id": 695, "districtid": 71, "text": "Sanphebagar Na. Pa.", "textNP": "साँफेबगर नगरपालिका"},
    {"id": 696, "districtid": 71, "text": "Turmakhad Ga. Pa.", "textNP": "तुर्माखाँद गाउँपालिका"},
    {"id": 697, "districtid": 72, "text": "Adharsha Ga. Pa.", "textNP": "आदर्श गाउँपालिका"},
    {"id": 698, "districtid": 72, "text": "Badikedar Ga. Pa.", "textNP": "बडीकेदार गाउँपालिका"},
    {"id": 699, "districtid": 72, "text": "Bogtan Ga. Pa.", "textNP": "बोगटान फुड्सिल गाउँपालिका"},
    {"id": 700, "districtid": 72, "text": "Dipayal Silgadi Na. Pa.", "textNP": "दिपायल सिलगढी नगरपालिका"},
    {"id": 701, "districtid": 72, "text": "Jorayal Ga. Pa.", "textNP": "जोरायल गाउँपालिका"},
    {"id": 702, "districtid": 72, "text": "K I Singh Ga. Pa.", "textNP": "के.आई.सिं. गाउँपालिका"},
    {"id": 703, "districtid": 72, "text": "Purbichauki Ga. Pa.", "textNP": "पूर्वीचौकी गाउँपालिका"},
    {"id": 704, "districtid": 72, "text": "Sayal Ga. Pa.", "textNP": "सायल गाउँपालिका"},
    {"id": 705, "districtid": 72, "text": "Shikhar Na. Pa.", "textNP": "शिखर नगरपालिका"},
    {"id": 706, "districtid": 73, "text": "Bardagoriya Ga. Pa.", "textNP": "बर्दगोरिया गाउँपालिका"},
    {"id": 707, "districtid": 73, "text": "Bhajani Na. Pa.", "textNP": "भजनी नगरपालिका"},
    {"id": 708, "districtid": 73, "text": "Chure Ga. Pa.", "textNP": "चुरे गाउँपालिका"},
    {"id": 709, "districtid": 73, "text": "Dhangadhi Up. Ma. Na. Pa.", "textNP": "धनगढी उपमहानगरपालिका"},
    {"id": 710, "districtid": 73, "text": "Gauriganga Na. Pa.", "textNP": "गौरीगंगा नगरपालिका"},
    {"id": 711, "districtid": 73, "text": "Ghodaghodi Na. Pa.", "textNP": "घोडाघोडी नगरपालिका"},
    {"id": 712, "districtid": 73, "text": "Godawari Na. Pa.", "textNP": "गोदावरी नगरपालिका"},
    {"id": 713, "districtid": 73, "text": "Janaki Ga. Pa.", "textNP": "जानकी गाउँपालिका"},
    {"id": 714, "districtid": 73, "text": "Joshipur Ga. Pa.", "textNP": "जोशीपुर गाउँपालिका"},
    {"id": 715, "districtid": 73, "text": "Kailari Ga. Pa.", "textNP": "कैलारी गाउँपालिका"},
    {"id": 716, "districtid": 73, "text": "Lamkichuha Na. Pa.", "textNP": "लम्कीचुहा नगरपालिका"},
    {"id": 717, "districtid": 73, "text": "Mohanyal Ga. Pa.", "textNP": "मोहन्याल गाउँपालिका"},
    {"id": 718, "districtid": 73, "text": "Tikapur Na. Pa.", "textNP": "टिकापुर नगरपालिका"},
    {"id": 719, "districtid": 74, "text": "Bedkot Na. Pa.", "textNP": "वेदकोट नगरपालिका"},
    {"id": 720, "districtid": 74, "text": "Belauri Na. Pa.", "textNP": "बेलौरी नगरपालिका"},
    {"id": 721, "districtid": 74, "text": "Beldandi Ga. Pa.", "textNP": "बेलडाडी गाउँपालिका"},
    {"id": 722, "districtid": 74, "text": "Bhimdatta Na. Pa.", "textNP": "भीमदत्त नगरपालिका"},
    {"id": 723, "districtid": 74, "text": "Krishnapur Na. Pa.", "textNP": "कृष्णपुर नगरपालिका"},
    {"id": 724, "districtid": 74, "text": "Laljhadi Ga. Pa.", "textNP": "लालझाडी गाउँपालिका"},
    {"id": 725, "districtid": 74, "text": "Mahakali Na. Pa.", "textNP": "महाकाली नगरपालिका"},
    {"id": 726, "districtid": 74, "text": "Punarbas Na. Pa.", "textNP": "पुर्नवास नगरपालिका"},
    {"id": 727, "districtid": 74, "text": "Shuklaphanta Na. Pa.", "textNP": "शुक्लाफाँटा नगरपालिका"},
    {"id": 728, "districtid": 75, "text": "Ajaymeru Ga. Pa.", "textNP": "अजयमेरु गाउँपालिका"},
    {"id": 729, "districtid": 75, "text": "Alital Ga. Pa.", "textNP": "आलिताल गाउँपालिका"},
    {"id": 730, "districtid": 75, "text": "Amargadhi Na. Pa.", "textNP": "अमरगढी नगरपालिका"},
    {"id": 731, "districtid": 75, "text": "Bhageshwar Ga. Pa.", "textNP": "भागेश्वर गाउँपालिका"},
    {"id": 732, "districtid": 75, "text": "Ganayapdhura Ga. Pa.", "textNP": "गन्यापधुरा गाउँपालिका"},
    {"id": 733, "districtid": 75, "text": "Nawadurga Ga. Pa.", "textNP": "नवदुर्गा गाउँपालिका"},
    {"id": 734, "districtid": 75, "text": "Parashuram Na. Pa.", "textNP": "परशुराम नगरपालिका"},
    {"id": 735, "districtid": 76, "text": "Dasharathchanda Na. Pa.", "textNP": "दशरथचन्द नगरपालिका"},
    {"id": 736, "districtid": 76, "text": "Dilasaini Ga. Pa.", "textNP": "डीलासैनी गाउँपालिका"},
    {"id": 737, "districtid": 76, "text": "Dogadakedar Ga. Pa.", "textNP": "दोगडाकेदार गाउँपालिका"},
    {"id": 738, "districtid": 76, "text": "Melauli Na. Pa.", "textNP": "मेलौली नगरपालिका"},
    {"id": 739, "districtid": 76, "text": "Pancheshwar Ga. Pa.", "textNP": "पञ्चेश्वर गाउँपालिका"},
    {"id": 740, "districtid": 76, "text": "Patan Na. Pa.", "textNP": "पाटन नगरपालिका"},
    {"id": 741, "districtid": 76, "text": "Purchaudi Na. Pa.", "textNP": "पुर्चौडी नगरपालिका"},
    {"id": 742, "districtid": 76, "text": "Shivanath Ga. Pa.", "textNP": "शिवनाथ गाउँपालिका"},
    {"id": 743, "districtid": 76, "text": "Sigas Ga. Pa.", "textNP": "सिगास गाउँपालिका"},
    {"id": 744, "districtid": 76, "text": "Surnaya Ga. Pa.", "textNP": "सुर्नया गाउँपालिका"},
    {"id": 745, "districtid": 77, "text": "Apihimal Ga. Pa.", "textNP": "अपिहिमाल गाउँपालिका"},
    {"id": 746, "districtid": 77, "text": "Byas Ga. Pa.", "textNP": "ब्याँस गाउँपालिका"},
    {"id": 747, "districtid": 77, "text": "Dunhu Ga. Pa.", "textNP": "दुहुँ गाउँपालिका"},
    {"id": 748, "districtid": 77, "text": "Lekam Ga. Pa.", "textNP": "लेकम गाउँपालिका"},
    {"id": 749, "districtid": 77, "text": "Mahakali Na. Pa.", "textNP": "महाकाली नगरपालिका"},
    {"id": 750, "districtid": 77, "text": "Malikaarjun Ga. Pa.", "textNP": "मालिकार्जुन गाउँपालिका"},
    {"id": 751, "districtid": 77, "text": "Marma Ga. Pa.", "textNP": "मार्मा गाउँपालिका"},
    {"id": 752, "districtid": 77, "text": "Naugad Ga. Pa.", "textNP": "नौगाड गाउँपालिका"},
    {"id": 753, "districtid": 77, "text": "Shailyashikhar Na. Pa.", "textNP": "शैल्यशिखर नगरपालिका"}
  ]
};
